### ISSUE TITLE
cannot install into a PCL 78 project

### ISSUE THREAD

**Issue by benoitjadinon** [canton7/RestEase#1]
Could not install package 'RestEase 1.0.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by benoitjadinon** [comment]
so I'm contacting the package author ;)

**Comment by canton7** [comment]
It requires a TypeBuilder, which is only available in .net projects and not pcls. I'm considering changing things so that this restriction is lifted for 2.0, but for now Refit is probably what you're at after, unfortunately.

**Comment by benoitjadinon** [comment]
oh ok, too bad ;) thanks

**Comment by canton7** [comment]
Sorry :( It's one of the trade-offs I made for not having `RefitStubs.cs` in your project.

**Comment by benoitjadinon** [comment]
what's the issues with the stub ? besides having an ugly random file laying around ? cause if its the only issue blocking the use on mobile platforms, it's too bad

**Comment by canton7** [comment]
Mainly an ugly random file that constantly changes lying around. Also, I wanted more intelligence in the auto-generated interface implementation: it means we can get away with less reflection, less boxing, things like method overloads work with issue, etc. Also auto-generating IL is much easier than auto-generating C#.

I've got plans to generate the interface implementations at compile-time and inject them into the assembly being compiled, but that's a little way off (I need to get my head around Mono.Cecil first...)

**Comment by ravensorb** [comment]
Curious if you've gotten back to this?  Would LOVE to use this in my Xamarin apps

**Comment by canton7** [comment]
I went down the route of supporting .net core instead: I support netstandard1.3. I'm not sure where that sits in the PCL nomenclature... The [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) implies that Xamarin supports all netstandard versions.

There were plans to use the source generation features of VS15 to support a wider range of netstandard versions, but they were canned. I then considered using Fody, but that doesn't yet have .net core support either..
