### ISSUE TITLE
Use correct custom deserializer based on content-type header

### ISSUE THREAD

**Issue by AeonDave** [canton7/RestEase#100]
Hello!

i understand how i can create my own deserializer.
but how i can use the correct one based on response header?

for example i'm contacting an api which respond with: Content-type: "application/json" or "application/x-protobuf"

and exist somewhere  a custom serializer/deserializer for protobuf out of the box?

thank you!

**Comment by canton7** [comment]
> but how i can use the correct one based on response header?

[See the FAQ](https://github.com/canton7/RestEase#i-may-get-responses-in-both-xml-and-json-and-want-to-deserialize-both)

> and exist somewhere a custom serializer/deserializer for protobuf out of the box?

No, but [writing your own serializers/deserializers is easy](https://github.com/canton7/RestEase#custom-serializers-and-deserializers).

**Comment by AeonDave** [comment]
Thank you!
i like your project so much.
D

**Comment by AeonDave** [comment]
Maybe could be useful (or there is a better way)

 ```
public class HybridResponseDeserializer : ResponseDeserializer
    {
        private static readonly JsonResponseDeserializer Json = new JsonResponseDeserializer();
        private static readonly ProtobufResponseDeserializer Protobuf = new ProtobufResponseDeserializer();
        private static readonly XmlResponseDeserializer Xml = new XmlResponseDeserializer();

        public override T Deserialize<T>(string content, HttpResponseMessage response, ResponseDeserializerInfo info)
        {
            var type = response.Content.Headers.ContentType.MediaType;
            if (type.ToLower().Contains("json"))
                return Json.Deserialize<T>(content, response, info);
            if (type.ToLower().Contains("xml"))
                return Xml.Deserialize<T>(content, response, info);
            if (type.ToLower().Contains("protobuf"))
                return Protobuf.Deserialize<T>(content, response, info);
            return Json.Deserialize<T>(content, response, info);
        }
    }
```

```
public class ProtobufResponseDeserializer : ResponseDeserializer
    {
        private static readonly Lazy<RuntimeTypeModel> model = new Lazy<RuntimeTypeModel>(CreateTypeModel);
        public static RuntimeTypeModel Model => model.Value;

        public override T Deserialize<T>(string content, HttpResponseMessage response, ResponseDeserializerInfo info)
        {
            return Task.Run(async () =>
                (T)Model.Deserialize(await response.Content.ReadAsStreamAsync().ConfigureAwait(false), null,
                    typeof(T))).Result;
        }

        private static RuntimeTypeModel CreateTypeModel()
        {
            var typeModel = TypeModel.Create();
            typeModel.UseImplicitZeroDefaults = false;
            typeModel.AllowParseableTypes = true;
            return typeModel;
        }
    }
```

**Comment by canton7** [comment]
> `type.ToLower().Contains("xml")`

Don't do this. Use `type.IndexOf("json", StringComparison.OrdinalIgnoreCase) >= 0`. Although it would be much better to match on the entire MediaType, rather than looking for a substring.

> `return Task.Run(async () =>
                (T)Model.Deserialize(await response.Content.ReadAsStreamAsync().ConfigureAwait(false), null,
                    typeof(T))).Result;`

This is pointless: you're spinning off a new Task, and then synchronously waiting for it to complete.

**Comment by AeonDave** [comment]
> This is pointless: you're spinning off a new Task, and then synchronously waiting for it to complete.

it's a misprint.
the only way i can get a Stream from the response is getting it from ReadAsStreamAsync which is an async task
`return (T) Model.Deserialize(response.Content.ReadAsStreamAsync().Result, null, typeof(T));`
is ok?

**Comment by canton7** [comment]
It's no worse than spinning off a new Task, and then calling `.Result` on that new Task...

From the README:

> If however you return a Task<T>, Task<string>, or Task<Response<T>>, then HttpCompletionOption.ResponseContentRead is used, meaning that any CancellationToken that you pass will cancel the body download

So `Deserialize` is only called once the content has been fetched, so `response.Content.ReadAsStreamAsync()` won't need to do any work - it will already have fetched the result. So it should return an already-completed Task.

**Comment by AeonDave** [comment]
uhm, ok but
how i can get the stream of the Content inside the `Deserialize<T> ` overridden method? i cannot find any other way, and my solution written above works

**Comment by canton7** [comment]
Using `response.Content.ReadAsStreamAsync().Result`. What you said was correct. I was justifying *why* it was correct.

**Comment by AeonDave** [comment]
Oh perfect!
thank you for the support!
