### ISSUE TITLE
Question: Content negotiation / multiple deserializers

### ISSUE THREAD

**Issue by shatl** [canton7/RestEase#103]
Hello,
Is this supported? 

E.g. I have a service which can return response in Json, XML and binary format (depending on Accept header value).

**Comment by canton7** [comment]
There's no built-in support for content negotiation. [You can set the Accept header yourself ](https://github.com/canton7/RestEase#headers), or you can [accept multiple response content-types](https://github.com/canton7/RestEase#i-may-get-responses-in-both-xml-and-json-and-want-to-deserialize-both).

**Comment by shatl** [comment]
Awesome, thanks for quick response!
