### ISSUE TITLE
Query as complex object

### ISSUE THREAD

**Issue by RomanKernSW** [canton7/RestEase#104]
Hi, I couldn't find anything that can support query as complex object.
The problem is, if I have more then 2 query parameters, its very useful to make a complex object where properties matches the query parameters.

Is their any implementation for this exists?

```c#

class MyQueryParameters{
    public string ParamA {get;set;}
    public string ParamB {get;set;}
    public string ParamC {get;set;}
}

interface IClient {
    Task Call([ComplexQuery] MyQueryParameters parameters);
}

var rest = RestClient.For<IClient>("https://www...");
rest.Call(new MyQueryParameters{...});

// url:  https://www.../Call?ParamA=xxx&ParamB=xxx&ParamC=xxx
```

**Comment by canton7** [comment]
There's nothing built-in (although it's related to #79). You can [write your own](https://github.com/canton7/RestEase#serializing-request-parameters-requestqueryparamserializer) though.
