### ISSUE TITLE
Please consider better handling of 404 HTTP status code

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [canton7/RestEase#105]
In my application getting HTTP 404 error codes happens on a daily basics e.g. often during validation stage I ask other services if a given entities exist. Currently I can handle 404's using `Response` class e.g.

```
public interface ISomeService {
        [Get("/v1/countries/{countryIsoCode}")]
        [AllowAnyStatusCode]
        Task<Response<Country>> GetCountryByIsoCode([Path]string countryIsoCode);
}

public async Task<bool> IsEUCountry(string countryIsoCode)
{
	using (var response = await _referentialApiClient.GetCountryByIsoCode(countryIsoCode))
	{
		if (response.ResponseMessage.StatusCode == HttpStatusCode.NotFound)
		{
			// Country not found
			return false;
		}
		else
		{
			return response.GetContent().IsEUCountry;
		}
	}
}
```

In my opinion this is so frequent case that it needs a special treatment. Usually when we get 404 we just want to return `null` from a given method. I propose to add a new attribute like `[NotFoundToNull]`. The example usage should be:
```
public interface ISomeService {
        [Get("/v1/countries/{countryIsoCode}")]
        [NotFoundToNull]
        Task<Country> GetCountryByIsoCode([Path]string countryIsoCode);
}
```
In this case when server returns 404 we should just get `null` country object. That would make my code much more easier.

**Comment by canton7** [comment]
Consider:

1. Subclassing Requester and overriding SendRequestAsync
2. Subclassing Requester, overriding RequestAsync, and catching the ApiException
3. Contributing a modification to Requester which extracts the ApiException-throwing behaviour into its own method, and overriding that.
3. Writing a RequestModifier which returns null if the response is 404
4. Using a custom ResponseDeserializer which throws / returns null as appropriate, along with `[AllowAnyStatusCode]`

In the long term, this really comes under better integration with Polly (#89).

**Comment by canton7** [comment]
In fact, anywhere you have an `IRequestInfo` (which is all of the above except RequestModifier), you have access to the MethodInfo, so you can easily add your own support for your own `[NotFoundToNull]`.

**Comment by marcin-chwedczuk-meow** [comment]
OK subclassing Requester looks like a good way to do it IMHO. Thanks for the response.
