### ISSUE TITLE
[FEATURE REQUEST] Please add a way to validate usage of attributes on interfaces

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [canton7/RestEase#106]
Let's say I have an interface:
```
public interface IUsersApiClient {
        [Get("/v1/users/by-domain/{domain}")]
        Task<IReadOnlyList<User>> GetUsersByDomain(string domain);
}
```
As we can see it contains an error (missing [Path] attribute). It would be nice if RE provided a test method similar to what FluentValidation (https://fluentvalidation.net/testing) or AutoMapper provide (http://docs.automapper.org/en/stable/Configuration-validation.html) to validate that API definitions are valid.

For example in unit test we could have:
```
RestClientUtil.CheckApiDefinition<IUsersApiClient>();
```
that would trow an exception in case of any errors.

**Comment by canton7** [comment]
RestClient.For should throw in that case?

**Comment by marcin-chwedczuk-meow** [comment]
OK, thanks for the answer. Indeed you are right. I put `RestClient.For` in my unit tests and it generates pretty decent error messages.

**Comment by canton7** [comment]
Cool, glad that works!
