### ISSUE TITLE
Handle HttpRequestException / ConnectFailure

### ISSUE THREAD

**Issue by Partovic** [canton7/RestEase#108]
Is there a proper way to avoid HttpRequestExceptions to be thrown if "AllowAnyStatusCode" is active?
While developing, my endpoint doesn't have a webservice running all the time. For now this results in a HttpRequestException when trying to make a request.

I already tried to use a custom WebRequestHandler which catches this specific execption in "SendAsync". Then it returns a new Instance of HttpResponseMessage with a configured StatusCode. But this results in a NullReferenceException:

> Exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. | StackTrace:    bei RestEase.Implementation.Requester.<RequestWithResponseAsync>d__37`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by canton7** [comment]
I'm guessing you forgot to assign a body to the response?

This worked for me:

```csharp
class Handler : HttpMessageHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var response = new HttpResponseMessage(HttpStatusCode.NotFound)
        {
            Content = new StringContent(string.Empty),
        };
        return Task.FromResult(response);
    }
}
```

**Comment by Partovic** [comment]
That was actually the missing part! My bad! Thanks for your quick answer!
Anyway, is this the correct way to implement such behaviour? Or do you suggest another way for this kind of scenario?

regards

**Comment by canton7** [comment]
This is what I would have suggested.

Reopening, as I shouldn't crash if there's no body....
