### ISSUE TITLE
Documentation - Variable Interface Headers

### ISSUE THREAD

**Issue by CraigSuddo** [canton7/RestEase#111]
The code under the Variable interface headers section, in code block two would be better as below;

```
public interface ISomeApi
{
    [Header("X-API-Key", "None")]
    string ApiKey { get; set; }

    [Get("users/{userName}")]
    Task<User> FetchUserAsync([Path] string userName);
}

ISomeApi api = RestClient.For<ISomeApi>("http://api.example.com")

// "X-API-Key: None"
var user = await api.FetchUserAsync("Bob");
```

Reason being, you've added a method to the interface example, then called a completely undefined method.

**Comment by canton7** [comment]
Right, s/FetchUserId/FetchUserAsync, thanks!

**Comment by CraigSuddo** [comment]
Yep, and the method parameters should be string userName as you're passing Bob in rather than a userId ;)

**Comment by canton7** [comment]
It's userId in all of the other examples, and userIds can be strings, so I think I'll leave that one.
