### ISSUE TITLE
ConfigureAwait(false) 

### ISSUE THREAD

**Issue by javicrespo** [canton7/RestEase#115]
Hi,

Would it make sense to add ConfigureAwait(false) to this class awaiters ?

https://github.com/canton7/RestEase/blob/afc4ca9095e3e3a1345bfa79a3b70cd4cd857fa1/src/RestEase/Implementation/ModifyingClientHttpHandler.cs#L36,L37

We are experiencing a deadlock issue when calling a service through the RestClient but we can't really pinpoint where exactly it comes from. We're running it in a xunit/SpecFlow setup which seems to be prone to task deadlocks (https://github.com/techtalk/SpecFlow/issues/1159)

However, if my poor understanding of Task synchronizationcontext serves me well, deadlocks can be avoided by adding configureAwait(false) in underlying library methods. 
We had a look at RestEase code base and we found some usages of configureAwait(false) 

https://github.com/canton7/RestEase/search?q=await&unscoped_q=await

But not in the ModifyingClientHttpHandler class.

**Comment by canton7** [comment]
Right, yes those need `ConfigureAwait(false)` on them. That's an oversight.

As a short-term fix, define your own subclass of `HttpHandler` which does what you want, then:

```csharp
var httpClient = new HttpClient(new YourHttpHandler())
{
    BaseAddress = new Uri("your base url"),
};
var client = RestClient.For<IYourInterface>(httpClient);
```
