### ISSUE TITLE
Feature proposal: [RequestProperty] attribute

### ISSUE THREAD

**Issue by Husqvik** [canton7/RestEase#116]
For few specific cases it would be nice to have ability to pass specific API parameters as request properties.

example:
```
[Get("/foo")]
Task Foo([RequestProperty("myKey")] object myObjectIWantToAccessFromDelegatingHandler);
```

delegating handler:
```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    var myObjectIWantToAccessFromDelegatingHandler = request.Properties["myKey"];
    ...
}
```

**Comment by canton7** [comment]
Sounds fine. It might take me a while to get around to it, though - there are higher-priority issues on the backlog.

If you fancy having a crack, start off in RequestInfo, then edit ImplementationBuilder to interpret the new parameter and add it to the RequestInfo, then header over to Requester which will put it into the HttpRequestMessage.

**Comment by canton7** [comment]
Implemented, thanks @Husqvik!
