### ISSUE TITLE
Query parameter is not URI safe

### ISSUE THREAD

**Issue by Avabin** [canton7/RestEase#119]
I'm trying to use DateTimeOffset as a query parameter as shown below.
```csharp
[Get("api/DateTimeOffsetEndpoint")]
Task<SomeDto> FetchSomeDto([Query(Format = "yyyy-MM-ddTHH:mm:ss.fffZ", SerializationMethod = QuerySerializationMethod.ToString)] DateTimeOffset dateTimeOffset);
```
What I get in request URl is `2019-05-24T12:48:51.777Z` and not `2019-05-24T12%3A48%3A51.777Z` .

As you see, serialized value contains characters that are not URI safe.

**Comment by canton7** [comment]
Are you sure about that?

Firstly, your example is invalid, as you're mixing query and path parameters, and will throw an exception when you call `RestClient.For<...>()`. I suspect you meant simply:

```csharp
[Get("api/DateTimeOffsetEndpoint")]
Task FetchSomeDto([Query(Format = "yyyy-MM-ddTHH:mm:ss.fffZ", SerializationMethod = QuerySerializationMethod.ToString)] DateTimeOffset dateTimeOffset);
```

They are escaped: [here](https://github.com/canton7/RestEase/blob/5d26b2e35dbfd6f0cfdaf57f74c754a51cb780bc/src/RestEase/Implementation/Requester.cs#L202). I wrote a quick unit test, and the `:`'s were escaped.

![image](https://user-images.githubusercontent.com/568104/58324838-ef933a00-7e1f-11e9-8847-2143b9a8b240.png)

Note that `Uri.ToString()` does not show the escape sequences - you need to look at `Uri.AbsoluteUri`.

In fiddler:

![image](https://user-images.githubusercontent.com/568104/58325060-852ec980-7e20-11e9-8e46-e2db0fd9df82.png)

**Comment by Avabin** [comment]
I'm not mixing query and path parameter, this was a mistake made by me while "anonymizing" my code.
