### ISSUE TITLE
Path Parameter is not encoded properly for white spaces

### ISSUE THREAD

**Issue by ketan-s** [canton7/RestEase#12]
My path parameter has a white space in it and the space is encoded by '+' sign which actually need to be encoded with %20 so my webapi controller understand these url encode and can do a urldecode by itself.

Note: A code needs to be changed in RestEase.Implementation.Requester.SubstitutePathParameters method where HttpUtility.UrlEncode need to be updated by HttpUtility.UrlPathEncode

**Comment by canton7** [comment]
Oops, yeah you're right. Let me get that fixed....

**Comment by ketan-s** [comment]
Do you have any time line when will new version will get released with the given fix?

**Comment by canton7** [comment]
`HttpUtility.UrlPathEncode` didn't do the trick: it didn't escape characters like `?` or `&`. It's behaviour also changed recently, and the MSDN page says "Don't use", so I'm quite reluctant...

There doesn't actually appear to be a built-in method to do what I want, as far as I can find. Still working on it.
