### ISSUE TITLE
Detecting 401 unauthorized for all request

### ISSUE THREAD

**Issue by musab1234** [canton7/RestEase#122]
Whenever any api return 401 unauthorized status code, i want to redirect to logout page. I am using asp.net core 2.1 , any  extension or attribute through which i can achieve that? . There are number of requests so i can not check using try catch. 

Thank you.

**Comment by canton7** [comment]
Redirect in what sense? Normally it's the HTTP server which has the logic "if the request is not authorized, then send a Location header to redirect the client", not the client.
