### ISSUE TITLE
QueryString params have + instead of %20?

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#124]
I am working with RestEase again and one of the APIs I am trying to hit is throwing on an error on a GET request and when I was troubleshooting it I noticed that a + is being used for spaces rather than %20 when i am passing a string with spaces in it.  I did a little digging into the code and I saw that in [Requester.cs:184](https://github.com/canton7/RestEase/blob/5d26b2e35dbfd6f0cfdaf57f74c754a51cb780bc/src/RestEase/Implementation/Requester.cs#L184) there is an explicit find/replace and I was curious as to why -- wouldn't that be forcing partial "form encoding" on a query string param?

**Comment by canton7** [comment]
IIRC, both `+` and `%20` are valid in the query string (but only `%20` is valid in the path). 

Looking back at the history, it looks like the original reason is that `HttpUtility.ParseQueryString.Add` encodes spaces as `+` (which RestEase used, once upon a time, before migrating to .NET Standard), and everything since then has been about maintaining the same behaviour.

**Comment by ravensorb** [comment]
Hmm, I thought the + was more of an "allowed" character rather than part of the spec. 

Thanks for thee quick response!

**Comment by canton7** [comment]
See "Query strings" [here](https://www.w3.org/Addressing/URL/uri-spec.html).

It might be that `%20` is an objectively better choice - in the earlier versions of RestEase I didn't think too hard about this, and just used whatever the Framework libraries thought was best (which was to use `+`). After that, it was all about not changing the behaviour between versions.

**Comment by ronnieoverby** [comment]
So what is the easiest way to use `%20` instead of `+` when encoding query string parameters?

**Comment by ronnieoverby** [comment]
Here's a way:

```C#
public class MyRequester(HttpClient client) : Requester(client)
{
	protected override string BuildQueryParam(string initialQueryString, IEnumerable<RawQueryParameterInfo> rawQueryParameters, IEnumerable<QueryParameterInfo> queryParams, IEnumerable<QueryParameterInfo> queryProperties, IRequestInfo requestInfo)
	{
		return base
			.BuildQueryParam(initialQueryString, rawQueryParameters, queryParams, queryProperties, requestInfo)
			.Replace("+", "%20");
	}
}
```

Between RestEase replacing %20's and this custom requester re-replacing the +'s, there's a lot of needless string allocations. It would be cool if Restease allowed disabling the %20 replacements to begin with.
