### ISSUE TITLE
Serialize collection?

### ISSUE THREAD

**Issue by bdaniel7** [canton7/RestEase#125]
I'm trying to pass a query string that contains collections, like this:
/audit/get-entries?Page=1&Results=5&SortBy[0].Column=AuditDate&SortBy[0].Direction=Asc&Filters[0].Column=userName&Filters[0].Value=daniel&Filters[0].Operator=Contains

The interface is defined like this:
```
[SerializationMethods(Query = QuerySerializationMethod.Serialized)]
public interface IAuditService
{
	[AllowAnyStatusCode]
	[Get("audit/get-entries")]
	Task<PagedResult<AuditEntryDto>> GetAudit ([Query] BrowseAudit query);
}

public class BrowseAudit
{
   public int Page { get; set; };
   public int Results { get; set; };
   public List<SortDescriptor> SortBy { get; set; }
}

public class SortDescriptor : IEquatable<SortDescriptor>
{
		public string Column { get; set; }

		/// <summary>
		/// Defaults to Ascending
		/// </summary>
		public SortDirection Direction { get; set; }
}
```
Is this supported by default?

**Comment by canton7** [comment]
RestEase doesn't support serializing objects into the query string like that, unless you provide a custom query parameter serializer.

There are two ways of doing this. You can use [`[QueryMap]`](https://github.com/canton7/RestEase#query-parameters-map), or you can use a [custom query parameter serializer](https://github.com/canton7/RestEase#serializing-request-query-parameters-requestqueryparamserializer).

**Comment by canton7** [comment]
Something like:

```csharp
if (value == null)
    yield break;

yield return new KeyValuePair<string, string>("Page", value.Page);
yield return new KeyValuePair<string, string>("Results", value.Results);
for (int i = 0; i < value.SortBy.Count; i++)
{
    yield return new KeyValuePair<string, string>($"SortBy[{i}].Column", value.SortBy[i].Column);
    yield return new KeyValuePair<string, string>($"SortBy[{i}].Direction", value.SortBy[i].Direction);
}
```

**Comment by bdaniel7** [comment]
I implemented something that actually works, but the generated url looks like this:

http://localhost:5300/audit/get-entries?Page=1&Results=10&SortBy%5B0%5D.Column=AuditDate&SortBy%5B0%5D.Direction=Asc

**Comment by bdaniel7** [comment]
Can this escape be prevented? I tried to set the "unescape" flag when creating the URI for the client, but it doesn't work.

**Comment by canton7** [comment]
RestEase doesn't (currently) allow any control over the exact nature of escaping - it's assumed that, so long as the escaping is valid, the HTTP server will process it. If you've got a server which does not correctly process escaped characters, I'm afraid you're on your own!

I guess you could subclass Requester and override [this method](https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/Requester.cs#L153).

What "unescape" flag do you mean?

**Comment by bdaniel7** [comment]
The only problem with escaped query strings is that they are ugly. But I'll get over it.

https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-2.1#System_Uri__ctor_System_String_System_Boolean_

**Comment by canton7** [comment]
Aha, that one. Yeah that won't have an effect, as we escape the query string before it interacts with Uri. Finding an effective BCL method to escape query strings which is available in all of the places that RestEase targets is hard, and `Uri.EscapeDataString` does a good job (apart from some unnecessary escapes). I suppose I could make the actual escaping method pluggable...
