### ISSUE TITLE
AppDomain Crash after RequestWithResponseAsync in netcore 2.0 app

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#126]
I am running into an odd issue and I am having a difficult time tracking it down.  Right now if I run a NUnit test on my code it works 100% and if I call the exact same code from a netcore 2.0 app it crashes (hard crash, no exception, app domain exists) in a RestEase call. I created a custom Requester and started stepping through and the last call made is in RequestWithResponseAsync before the app domain just exists.  Any suggestions on tracking this down?

Edit: I have tried using 1.4.9 and 1.4.10 -- same behavior in both (works in unit test, crashes hard in netcore app)

**Comment by canton7** [comment]
What was it, out of curiosity?

**Comment by ravensorb** [comment]
It looks like a conflict in running the RestEase client inside an async main method for the exe.  I am still looking for the exact cause however I was able to at least determine that if I switched to a standard method and then wrapped the call in a Task it started working.  Still a bit odd -- its been a long time since I had the entire app domain disappear with 0 details (not even an eventlog record).

**Comment by canton7** [comment]
Huh, I helped someone with a similar issue on IRC earlier today. Their issue was that they were using notepad++, which knew how to compile `async Task Main`, but didn't seem to know how to correctly wait for the Task to complete when running it. Any chance you're doing something similar -- running the application in a non-standard environment?

Just to check, is your main method `async void` or `async Task`?

**Comment by ravensorb** [comment]
Good question -- it's ```async Task Main(string[] args)```

Some more details:  If I call RestEase in an async Action or delegate when using an async Task Main -- the entire app goes down.  Interesting thing is, I can call an httpclient.GetAsync to the same end point and no issues at all.

**Comment by canton7** [comment]
> If I call RestEase in an async Action or delegate

That's somewhat expected (if by "goes down" you mean "exits normally"). `Action` by definition does not return anything, so it cannot return a `Task`, so `Main` has no way of knowing when the request has completed. An async Action is the same as an `async void` method. You'll probably want an `async Func<Task>`.

Have you got some code you can share which reproduces the issue?
