### ISSUE TITLE
New RestClient Errors

### ISSUE THREAD

**Issue by AeonDave** [canton7/RestEase#128]
Hello,
In Serialization of Path Parameters chapter you wrote
`
ISomeApi = new RestClient
{
    RequestPathParamSerializer = new StringEnumRequestPathParamSerializer()
}.For<ISomeApi>("http://api.example.com");
`

But this snippet don't work.
That's because new RestClient need some args and For from a non static RestClient "cannot be accessed from an instance reference"

it is correct?

**Comment by canton7** [comment]
Correct, that doc is wrong. It should be `new RestClient("http://....") { RequestPathParamSerializer = ... }.For<ISomeApi>()`

**Comment by AeonDave** [comment]
Thank you!
I have another question:

I need to build a Rest client with a base http address and a generic path for a downloader (which don't know any paths)

I would like to have an Interface like this
```
public interface IGenericPath
    {
        [Get("{path}")]
        Task<Stream> GetStream(string path);
    }
```

and a provider constructor like this:

```
Api = new RestClient(GetHttpClient(uri, timeout, customHeaders))
            {
                ResponseDeserializer = new HybridResponseDeserializer(),
                RequestBodySerializer = new HybridRequestBodySerializer()
            }.For<T>();
```
I need to build restclient with custom deserializer.
(T is IGenericPath)
Now if i call
```
var PathAndQuery = "/test/randomguid/filename.dat"
var file = await Api.GetStream(PathAndQuery);
```

throws 
"Method 'GetStream': unable to find a [Path("path")] property or parameter for the path placeholder '{path}'."

this happens even with

```
 [Get("{key}")]
 Task<Stream> GetStream<TKey>(TKey key);
```
or
```
public interface IGenericPath<TKey>
{
    [Get("{key}")]
    Task<Stream> GetStream(TKey key);
}
```
like described in Using Generic Interfaces.

I know that the description states that i have to use the static constructor, but i cannot because i need to use a custom httpclient and custom deserializers.

> RestClient.For<IReallyExcitingCrudApi<User, string>>("http://api.example.com/users");

So, is it possible to use a custom generic interface and build a custom RestClient
with a base url like "http://test.com"
for calling different path like
"/test/file.dat"
"/random//randomtest/file.dat"
"../music.mp4"
ecc..

Thank you!

**Comment by canton7** [comment]
You need to use `[Path]` to mark the parameter as filling in a path placeholder, e.g. `Task<Stream> GetStream([Path] string path)`. [See the README](https://github.com/canton7/RestEase#path-parameters)

**Comment by canton7** [comment]
I've opened https://github.com/canton7/RestEase/issues/129 to fix the "Using Generic Interfaces" bit of the README.

**Comment by AeonDave** [comment]
Yeah true i forgot that. :)
But if i pass "/random/randomtest/file.dat" the path is being UrlEncoded
"%2Frandom%2Frandomtest%2Ffile.dat"

there is any way to avoid this behavior?
Thank you and sorry for all the questions
D

**Comment by AeonDave** [comment]
NVM thank you i got it!
`GetStream([Path(UrlEncode = false)]`

ty for all

**Comment by canton7** [comment]
Closing as resolved
