### ISSUE TITLE
AllowAnyStatusCode - not allowed on parent interface

### ISSUE THREAD

**Issue by netclectic** [canton7/RestEase#131]
A small issue with the readme...

> you can apply [AllowAnyStatusCode] to you method, or indeed to the whole interface,

If I apply it to the whole interface then I get an exception telling me it's now allowed.

**Comment by canton7** [comment]
Can you share an example of what you're trying, which fails?

I've got [unit tests](https://github.com/canton7/RestEase/blob/3e2cd314ad109bd6f3465f88fedebdb4d5023c0d/src/RestEaseUnitTests/ImplementationBuilderTests/AllowAnyStatusCodeTests.cs#L28) which verify that this works.

**Comment by netclectic** [comment]
with RestEase v1.4.10

I'm targeting 'netcoreapp3.0' on preview 8, so I guess it may be something platform specific. 

```
        public interface ITestApi
        {
            [Get("foo")]
            Task GetFoo();
        }

        [Fact]
        public void AllowAnyStatusCode_On_Interface_ShouldBeAllowed()
        {
            var restClient = new RestClient("http://localhost").For<ITestApi>();
            Assert.NotNull(restClient);
        }
```

results in...

> RestEase.Implementation.ImplementationCreationException : Parent interface IIBMCommunitiesApi may not have any [AllowAnyStatusCode] attributes
>  Stack Trace:
>    at RestEase.Implementation.ImplementationBuilder.BuildImplementationImpl(Type interfaceType)
>    at RestEase.Implementation.ImplementationBuilder.CreateImplementation[T](IRequester requester)
>    at RestEase.RestClient.For[T]()

**Comment by canton7** [comment]
You don't have `[AllowAnyStatusCode]` anywhere in that sample?

**Comment by netclectic** [comment]
sorry, copy and paste error, the interface should be...

```
        [AllowAnyStatusCode]
        public interface ITestApi
        {
            [Get("foo")]
            Task GetFoo();
        }
```

**Comment by canton7** [comment]
Where is `IIBMCommunitiesApi`?

I think you're over-simplifying your sample. At the very least, you should only get that message when you have inheritance, which your sample doesn't show.

**Comment by netclectic** [comment]
Ok, that's weird. I moved the same test into a clean test project and it works there. Restarted VS and now the other one passes too.

The original one, as you suggested, was using interface inheritance. So that'll explain it.

Thanks and apologies for the wild goose chase!

**Comment by canton7** [comment]
No worries, glad you found the issue!

**Comment by canton7** [comment]
That exception message is entirely the opposite of what it means, though! I'll fix that.

**Comment by Tadimsky** [comment]
@canton7 I'm getting something similar, but I must be misunderstanding.

I have the following:

```csharp

[AllowAnyStatusCode]
public interface IServiceApi
{
}

public interface IAuthenticatedServiceApi : IServiceApi
{
    ...
}

public interface ITenantSettingsClient : IAuthenticatedServiceApi
{
    ...
}
```

When I do `RestClient.For<ITenantSettingsClient>` I get the following error:

```
RestEase.Implementation.ImplementationCreationException: 'Parent interface IServiceApi may not have any [AllowAnyStatusCode] attributes'
```

Since `IServiceApi` is the root interface, it should be allowed, right?

**Comment by canton7** [comment]
I managed to confuse myself. The exception message is right, but the README is wrong.

You're only allowed `[AllowAnyStatusCode]` on the child-most interface. I think the README is also wrong about `[Header]` - there doesn't seem to be anything in the code which prohibits headers on both parent and child: they're combined.

I think a more sensible rule would be to disallow e.g. `[AllowAnyStatusCode]` on the parent and `[AllowAnyStatusCode(false)]` on the child.
