### ISSUE TITLE
README around [AllowAnyStatusCode] on child interfaces is incorrect

### ISSUE THREAD

**Issue by canton7** [canton7/RestEase#132]
See #131.

We should probably also allow `[AllowAnyStatusCode]` on the parent as well, so long as the parent/child don't conflict.

**Comment by ei-en-kei** [comment]
It might be a good idea as a future expansion, allow the header on both parent and child, with child having precedent over parent: so if parent allows and child disallows it should be disallowed. 

Allowing it on the parent without conflict would definitely unblock me at the moment!

**Comment by canton7** [comment]
One of the reasons that starts getting complicated is that:

1. You're allowed to do `[AllowAnyStatusCode(false)]`
2. Interfaces support multiple inheritance, so a child can have multiple parents

Therefore an interface can have multiple direct parents, each of which has a different idea of whether any status code should be allowed.

**Comment by canton7** [comment]
As things are now, you can unblock yourself by putting `[AllowAnyStatusCode]` on each of the parent interface's methods, rather than on the whole interface.
