### ISSUE TITLE
Feature Proposal: Make RequestInfo available to the RequestModifier

### ISSUE THREAD

**Issue by jonlorusso** [canton7/RestEase#133]
It would be useful to have access to the [RequestInfo](https://github.com/canton7/RestEase/blob/master/src/RestEase/IRequestInfo.cs) in the [RequestModifier](https://github.com/canton7/RestEase/blob/master/src/RestEase/RequestModifier.cs).  

To further explain, in my context, I would like to examine the attributes declared on the invoked method, and modify the request accordingly.

**Comment by canton7** [comment]
Seems sensible, should be easy by adding it to `HttpRequestMessage.Properties`.
