### ISSUE TITLE
The first method for uploading multipart form data doesn't work

### ISSUE THREAD

**Issue by davidshen84** [canton7/RestEase#134]
ref: https://github.com/canton7/RestEase/issues/38

When I try the **Wrapping other methods** technic, and use *WireMock.Net* to check the request, the request I got had no body content and the request URL is something like:

    http://localhost:52099/api/test1?content=System.Net.Http.MultipartFormDataContent

I think the body serializer did not work properly.

The 2nd method **Using IRequester directly** worked.

**Comment by canton7** [comment]
Can you post your code that you tried for for the *Wrapping other methods*? It looks like your body was interpreted as query data rather than a request body, so you probably forgot `[Body]`

**Comment by davidshen84** [comment]
Yes, I just found out I need to add the `[Body]` attribute to the parameter. I did not add in the first place because the document did not have it. So I guess you forgot it too. :)

**Comment by canton7** [comment]
Right you are! Opened an issue to fix that.

**Comment by StefH** [comment]
Nice that you use WireMock.Net to test ;-)
