### ISSUE TITLE
How do I get the response headers?

### ISSUE THREAD

**Issue by retailcoder** [canton7/RestEase#136]
I'm using this awesome library to work with the Shopify REST API and everything was like a dream, until Shopify threw a wrench and decided to deprecate its `limit` and `page` querystring parameters, and phase-in "[cursor-based navigation](https://help.shopify.com/en/api/guides/paginated-rest-results)", where they put links to the next page in the response headers.

I can't seem to find anything about *response* headers... am I missing something, or RestEase needs a new feature for this?

Thanks!

**Comment by retailcoder** [comment]
Looks like a case for passing my own httpclient singleton to one of the `.For<T>()` overloads.

**Comment by canton7** [comment]
You can use `Response<T>`?

**Comment by retailcoder** [comment]
@Canton7 hm, sounds promising, how would I access it?

**Comment by canton7** [comment]
[Response Message](https://github.com/canton7/RestEase/blob/master/src/RestEase/Response.cs#L19), then get the headers from that.

**Comment by retailcoder** [comment]
Ah, looks like I had missed the `Response<T>` bullet [here](https://github.com/canton7/RestEase#return-types) -- all dots connected, thanks again!

**Comment by canton7** [comment]
I'll add words like "response headers" to that bit of the README for people searching for that in future.

**Comment by canton7** [comment]
Turns out I already did this...
