### ISSUE TITLE
Support Default Value of Properties.

### ISSUE THREAD

**Issue by baoduy** [canton7/RestEase#137]
I would like to suggest to support default value of properties feature.

```csharp
public interface ISomeApi
{
    [Path("accountId", defaultValue="1")]
    int AccountId { get; set; }

    [Get("{accountId}/profile")]
    Task<Profile> GetProfileAsync();

    [Delete("{accountId}")]
    Task DeleteAsync([Path("accountId")] int accountId);
}
```

So when creating an API instance of there is no value provided it will pick up the defaultValue if available.

Thanks
Duy

**Comment by canton7** [comment]
The reason this makes me a little nervous is that then you'd be able to write:

```c#
Task DeleteAsync([Path("accountId", defaultValue="1")] int accountId = 2);
```

... which just looks confusing.

I'm curious about your specific example. Is that representation of something you're actually doing, or is it just for illustration?

If it is representation of something you're actually doing, could you explain why `AccountId` is configurable, but has a default value of 1? And why `GetProfileAsync` doesn't take an accountId, whereas `DeleteAsync` does?

I'm just wondering whether there's a better solution here.

**Comment by baoduy** [comment]
Hi @canton7 
my sample code is just for illustration purposes. When creating the clients API for some Restful API as sample below the apiVersion value is the same for most of Azure AD instances so that I would like to provide the default for ApiVersion property.

```csharp
 public interface IAzureAD
 {
        [Path(nameof(TenantId))]
        string TenantId { get; set; }

        [Path("api-version")]
        string ApiVersion { get; set; }
}
```

this would be archive with .Net Core 3.0 as it is supporting the Interface default implementation.

What I'm doing now is create a custom Attribute named DefaultValue and create a custom factory method to apply default value from attribute to the instance once activated.

So, please be closed the issue.

Thank for your reply.
Duy
