### ISSUE TITLE
.NET Core 3.0 - 404 - Not Found

### ISSUE THREAD

**Issue by krismrp** [canton7/RestEase#141]
We recently upgraded our project from .NET Core 2.2 to 3.0, after we did this our tests stopped working (worked before upgrade) because all of the routes get "404 Not Found". Have anybody else experienced the same issue or know how to solve it? I suspect this might have something to do with ASP.NET routing changes in 3.0?

**Comment by canton7** [comment]
Where is RestEase used in your setup, exactly? Are you using it from your test methods to request your routes?

If so, can you open up Fiddler, and make sure that the requests look the same under .NET Core 2.2 and 3.0?

**Comment by krismrp** [comment]
We are using it from our test methods to request our routes, yes. We are passing RestClient.For<T> an HttpClient created from a TestServer instance. No changes were made to the tests before the upgrade. I was not able to inspect the request when using HttpClient from TestServer.

**Comment by canton7** [comment]
Ah right, `TestServer`.

Can you try doing a request directly on the `HttpClient`, without using RestEase? See if you can write one which works on .NET Core 2.2, but not .NET Core 3.0. If you can do this, is narrows down the problem by showing that RestEase probably isn't the source of the issue.

**Comment by krismrp** [comment]
I tried using the`HttpClient`directly, it worked in 2.2, but failed in 3.0. Could there be a problem with it?

**Comment by canton7** [comment]
I suspect the problem is somewhere between asp.net core's routing and the `TestServer`. I'm afraid I'm not well-versed enough in asp.net core to help. Either way, it doesn't look like a RestEase issue.

**Comment by krismrp** [comment]
Thanks anyways, I'll investigate more and submit an issue when I figure out the appropriate place.
