### ISSUE TITLE
Unused query parameters are added with default values.

### ISSUE THREAD

**Issue by Excalib88** [canton7/RestEase#142]
Hello! Unused parameters are added with default values. Can i mark them with an attribute and if no value is assigned then just don't add them to the request? If there is no such functionality, then please tell me where the functionality for applying attributes to the request is implemented, I want to send the pull request with such functional

**Comment by canton7** [comment]
Isn't this [already the case](https://github.com/canton7/RestEase/#variable-query-parameters)?

> If you pass a value which is null, then the key is not inserted. If you pass any other value (e.g. emptystring) then the value is left empty.

**Comment by Excalib88** [comment]
@canton7 This works exclusively with nullable types, for example, datetime will return 01.01.0001. Maybe I'm wrong, but string is also inserted into the parameter (I use properties in the interface to pass parameters)

**Comment by canton7** [comment]
I'm not sure what you're suggesting, then? If you write:

```cs
void Foo(DateTime dt = default);
```

and then call `Foo()`, the compiler will turn that into a call to `Foo(default(DateTime))`. There's no way to tell that the user called `Foo()` and not `Foo(default(DateTime))`.

However, you can write:

```cs
void Foo(DateTime? dt = null);
```

Then if you call `Foo()`, the compiler turns that into `Foo(null)`, and we can spot that you passed `null`, which is what currently happens.

> but string is also inserted into the parameter

What do you mean by that, exactly?

**Comment by Excalib88** [comment]
@canton7 thx! Sorry for my question, I will try to check and in case of a negative result I will return! I really liked your project and I would like to contribute!

**Comment by canton7** [comment]
Closing as no response
