### ISSUE TITLE
Deserialization to Json : Deserialize<T> used or Content.ReadAsStreamAsync()?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#144]
Hello @canton7,

I think that you just use the newtonsoft `Deserialize<[]>` code to convert a response (string) to a json object?

However it seems that this needs much more memory, then using some Content.ReadAsStreamAsync?

# Normal memory allocation
![image](https://user-images.githubusercontent.com/249938/72613373-9daf9f00-392f-11ea-97f7-2385da8c54bc.png)

# Memory allocation when using this code:
``` c#
Business[] response;
using (var responseMessage = await api.GetBusinessAsync().ConfigureAwait(false))
{
    using (var stream = await responseMessage.Content.ReadAsStreamAsync().ConfigureAwait(false))
    {
        using (var streamReader = new StreamReader(stream))
        {
            using (var reader = new JsonTextReader(streamReader))
            {
                var serializer = new JsonSerializer();
                response = serializer.Deserialize<Business[]>(reader);
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/249938/72613364-97b9be00-392f-11ea-91ac-b889d33c22e0.png)

What are your thoughts?

**Comment by canton7** [comment]
Sure, except that changing this means changing the `ResponseDeserializer`, which is a breaking change.

**Comment by StefH** [comment]
Maybe add a new class `StreamResponseAsyncDeserializer` with a method:

``` c#
public class AsyncResponseDeserializer
{
    public virtual Task<T> DeserializeAsync<T>(HttpResponseMessage response, ResponseDeserializerInfo info)
    {
        throw new NotImplementedException();
    }
}
```

Which can be implemented with **System.Text.Json** like:
``` c#
public class JsonAsyncResponseDeserializer : AsyncResponseDeserializer
{
    public override async Task<T> DeserializeAsync<T>(HttpResponseMessage response, ResponseDeserializerInfo info)
    {
        using (var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
        {
            return await System.Text.Json.JsonSerializer.DeserializeAsync<T>(stream).ConfigureAwait(false);
        }
    }
}
```

**Comment by canton7** [comment]
I'm very reluctant to be half-Json.net, half-System.Text.Json. They use different attributes, have different custom serialization infrastructure, etc. I've put my eggs in the Json.net basket, and I don't think that switching is worth the pain (or even the right thing to do). That might change in the future, of course.

**Comment by canton7** [comment]
Actually, if we use `ResponseContentRead` (which I think we do in the `Task<T>` case?), the content stream can be read before we call `Content.ReadAsStreamAsync`. We've still got the issue that `ResponseDeserializer` expects a `string` though, but maybe that can be worked around.

**Comment by canton7** [comment]
The other consideration however is that `HttpClient` is quite good at figuring out the encoding of the response (from headers, etc, if necessary). Json.net isn't going to have that advantage, since it can only look at the stream. So we might break some cases by moving to a stream.
