### ISSUE TITLE
Question: is it possible to define a constant query parameter on interface

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#145]
Is it possible to define a constant query parameter on interface? This constant query parameter should be added for each request.

Like:
``` c#
public interface IFormRecognizerV2Api
{
  [Query("subscription-key")]
  string SubscriptionKey { get; set; }
```

I could not find this in the documentation? (Or did I miss it?)

**Comment by canton7** [comment]
https://github.com/canton7/RestEase#query-properties

**Comment by StefH** [comment]
Thanks
