### ISSUE TITLE
Authorization Header is not beared.

### ISSUE THREAD

**Issue by pluveto** [canton7/RestEase#148]
```
  [Header("Authorization")]
        AuthenticationHeaderValue Authorization { get; set; }
```
```
            this.BasicApi = RestClient.For<IAcesoBasicApi>(baseUrl, async (request, cancellationToken) =>
            {
                if (this.Token == null)
                {
                    return;
                }
                this.BasicApi.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Token", Sign());
            });
```

BasicApi is an api interface.

After requesting remote, api server response: Authentication header missing.

**Comment by canton7** [comment]
That code is being called after the `HttpRequestMessage` has been created. Changing properties on `IAcesoBasicApi` will affect the *next* request, but the current request has already been created.

You probably want to be assigning to `request.Headers.Authorization`. That will change the current request.

**Comment by pluveto** [comment]
Thank you, solved. My first mistake is what you mentioned, and another mistake is that Apache route rewriting do not redirect headers. 
This `.htaccess` file may be helpful for someone facing same problem:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L]
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0 # this line is required
```
