### ISSUE TITLE
Ability to set content encoding on a post?

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#149]
I was curious if there is a way to set the content encoding on a POST/PATCH call?

**Comment by canton7** [comment]
It's just a header -- set it the same as any other header. [Here](https://github.com/canton7/RestEase#constant-method-headers) or [here](https://github.com/canton7/RestEase#variable-method-headers).

**Comment by canton7** [comment]
Or use a `StringContent` as the body, I guess.

**Comment by canton7** [comment]
Huh, it looks like there's no `ContentType` on `HttpRequestHeaders`, so that might fail: I'll test it over lunch.

**Comment by canton7** [comment]
No, that does work fine: it's on `HttpContentHeaders`.

**Comment by ravensorb** [comment]
You mean setting it like this -- [Header(“Content-Type”, “application/json;charset=utf-16”)]

If so, I have tried that and the receiving end is always receiving utf-8.  Amy I missing something easy?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by canton7** [comment]
This works for me:

```csharp
class Program
{
    public static async Task Main()
    {
        var client = RestClient.For<ISomeApi>("https://webhook.site/34899cc6-ad18-4288-a0e3-b7982ef58c80");
        await client.ThingAsync("Foobar");
    }

}

public interface ISomeApi
{
    [Put("")]
    [Header("Content-Type", "application/xml; charset=utf16")]
    public Task ThingAsync([Body] string body);
}
```

See the recorded requests here: https://webhook.site/#!/34899cc6-ad18-4288-a0e3-b7982ef58c80/8f7c7c5a-4852-4866-ab9a-4a7b68306a3d/1:

![image](https://user-images.githubusercontent.com/568104/77906724-55dabb80-7280-11ea-8c6d-2d70441a1b3a.png)

**Comment by canton7** [comment]
If you've got a repro, I'm happy to take a look at it.

**Comment by ravensorb** [comment]
Thanks – let me double check that it’s not something between me and the API that is doing the translation first and I’ll let you know.

The quick help is very much appreciated!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by canton7** [comment]
Hi, any progress?

**Comment by canton7** [comment]
Closing as no response
