### ISSUE TITLE
Path and Query supported at the same time?

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#15]
I am trying to do something like this and am getting an error " Unable to find both a placeholder {name} and a [Path("name")] for parameter name."

```
[Get("/API/Account/{accountId}/Category")]
Task<Category> GetCategoryAsync([Path] string accountId, [Query("name")]string name);
```

Is it possible to leverage both a dynamic path and query string parameters at the same time?

**Comment by ravensorb** [comment]
The more I look at this, the less it makes sense.  I event tried 

```
[Get("/API/Account/1/Category")]
Task<Category> GetCategoryAsync(string name);
```
and
```
[Get("/API/Account/1/Category")]
Task<Category> GetCategoryAsync(string someParam);
```
and am still getting (for BOTH of the above)
```
Unable to find both a placeholder {name} and a [Path("name")] for parameter name."
```

So why is it looking for a Path "name"?? I feel like I am missing something simple :)

**Comment by canton7** [comment]
I'm afraid I can't reproduce this - I've added unit tests for your cases, but they pass (as expected).

I think something else is going on: maybe your build is failing, and you're not running the code you think you're running? Can you create a minimal project which just reproduces the problem, and send it to me?

**Comment by ravensorb** [comment]
I don't disagree.  I looked over the code and it is not making sense to me either.  Especially since I am hitting the issue in my own test cases (NUnit3 based). 

So I just tried to get the source code with the idea that I would debug through it to see what I could find.  The problem is, I cannot get your solution to load.

```
---------------------------
Microsoft Visual Studio
---------------------------
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\Projects\Github\RestEase\src\RestEase\RestEase.xproj
---------------------------
```

I am using VS2015 with Update 3 running on Windows 10 x64.  Is there something specific I need to install to get things working?

**Comment by canton7** [comment]
You need the .NET Core tooling and SDK installed. See https://www.microsoft.com/net/core#windows.

**Comment by ravensorb** [comment]
Hmm, the version that the project is leveraging is no longer available for download.  That said, I figured it out - turns out this was an issue in the "construction" of the dynamic class and I had a Get attribute on another method that was incorrect (any chance you could add the method name in the error message to help troubleshoot this)?

**Comment by canton7** [comment]
[I do](https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/ImplementationBuilder.cs#L698)?

**Comment by ravensorb** [comment]
Weird that in the error I was getting that wasn't included.  No worries, its all good now.  Thanks!

**Comment by canton7** [comment]
No idea why that might be, it's been present in the error message for ages. I can put it at the beginning if that would make it clearer?
