### ISSUE TITLE
add possibilty to have multiple RawQueryStrings

### ISSUE THREAD

**Issue by TraderMoe** [canton7/RestEase#151]
Hello,

I would be pleased to have RawQueryStrings to can be used multiple times.
I've just finished the implementation and cannot push the branch because i dont have access to create/push a feature branch. As I am new to github and I really dont know how this works now I would be glad to get some help.

Thank you and have a nice day.

**Comment by canton7** [comment]
Firstly, I'd be interested to know what the need is? What use-case are you solving?

To create a PR, you'll need to fork this repository, do the work in your fork, then create a PR from a branch in your work. See [this doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) and [this doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork), as well as [this](https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows) for some general background.

**Comment by TraderMoe** [comment]
Thanks for the fast reply :)
I want to have two objects within my query to have the interface looking lighter.

example

``` csharp
public interface IQueryApi{
    /// <summary>
    /// query all source apis configured in query api
    /// </summary>
    /// <param name="query">this query passed to n apis</param>
    /// <param name="options">Configures the query api calls to the configured n apis</param>
    /// <returns></returns>
    [Get]
    Task<QueryResult> Get([RawQueryString]Query query, [RawQueryString]Options options);
}

public class Query{
    public List<int> Ids { get; set; }
    public string SearchString { get; set; }
    public DateTime ViewDate { get; set; }
    //... right now up to 20 Props
}

public class Options{
    public QueryApiFilterOptions FilterOptions { get; set; }
    public List<string> SourceApis { get;set; }
}

public enum QueryApiFilterOptions
{
    ApplyFilter,
    OverrideFilter,
    IgnoreFilter
}

public class QueryResult{
    public List<Items> Items { get; set; }
    //... Summary of the input
}

```

I've tried to use the
``` [Query(QuerySerializationMethod.Serialized)] Query query ```
but my expected result would be to have a query like 
``` // Requests http://api.example.com/search?Ids=1&SearchString=Foo&ViewDate=2020-04-17 ```

So the easiest way was to use the [RawQueryString] because i already have an overwritten .ToString() that delivers the structure i expected (for passint to the other apis).

Thanks and greetings :)

**Comment by canton7** [comment]
Ah interesting, I hadn't considered that someone would use a custom object with their own query string serialization as a parameter to RawQueryString.

If you go to the [Pull requests](https://github.com/canton7/RestEase/pulls) tab, you can select that branch as the source of the pull request.

**Comment by TraderMoe** [comment]
If you want i can provide the "ObjectToQueryStringSerializer"

how it basiclly looks right now
```
public interface IBookApi{
    [Get]
    Task<Books> Get([RawQueryString]QueryObject query);
    //mybooks.com/search?Id=1&Title=CSharpForDummies&Isbn=978-3-527-71519-0&State=InStock
}


public class QueryObject {
    public int Id { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    [QueryName("Isbn")]
    public string InternationalStandardBookNumber { get; set; }

    [QueryIgnore]
    public double Price { get; set; }

    public State State { get; set; }
}

public enum State{
    InStock,
    InDelivery,
    Sold,
    Removed
}
```

**Comment by canton7** [comment]
I don't follow -- your `QueryObject` doesn't have an overridden `ToString` method?

**Comment by TraderMoe** [comment]
sorry now it has. I'll make a feature branch if you are interested :)

**Comment by canton7** [comment]
This sounds similar to #79. I've avoided going down the route of custom object serializers because writing something which solves everyone's use-cases gets complex fast.

That said, I still don't follow why you're not using a `RequestQueryParamSerializer` for this? I think it will cover your needs.

**Comment by canton7** [comment]
Righty, that's on NuGet
