### ISSUE TITLE
Maybe split abstractions and implementations in two different libraries?

### ISSUE THREAD

**Issue by paulreicherdt** [canton7/RestEase#154]
Hi,

first of all - thanks for a great library! This is really a time saver and a nice way to implement a type safe communication between services.

Just a suggestion - maybe to split abstractions like attributes, interfaces and implementation in two different libraries? Like Microsoft do it with all new .NET core libraries. This would make it possible to define API client in a tiny liibrary and e.g. publish it as nuget package, without all the implementation details for ReasEase. Other services could consume this specification library and add the ReasEase client library for communication itself. 

What do you think?

Kind regards
Paul

**Comment by canton7** [comment]
Glad you like it!

As things stand, I don't see much point? Referencing a larger assembly doesn't increase the size of your assembly, or your NuGet package. At some point the final application will have to reference the full RestEase assembly, which is always going to bring the cost of that into the application, once. RestEase is hardly large, either 😄 

There's an argument around not forcing libraries which just define the RestEase interfaces to take dependencies on RestEase's transient dependencies (i.e. Newtonsoft.Json and S.R.E), but 1) the dependency on S.R.E goes away in netstandard2.1, and 2) removing a mandatory on Newtonsoft.Json is I think a separate issue).

That said, see #150 -- I'll probably have to do this as part of supporting Source Generators.

**Comment by paulreicherdt** [comment]
That's true - at final state, the application will reference the full ReasEase and referencing larger assembly doesn't increase my assembly or NuGet. It just feels a bit uncomfortable - to reference all the implementation details and dependencies where I only need to define a public API for consumer :)

But ok, I see your point.

**Comment by canton7** [comment]
It's now recommended that library authors use RestEase.SourceGenerator, which generates interface implementations at compile-time, which will be used automatically by consumers.

These implementations necessarily need to reference RestEase types, and so these need to be available in the RestEase assembly you reference. So I don't think there's a case any more for referencing an assembly which only contains RestEase's attributes.
