### ISSUE TITLE
Peek serialized json payload?

### ISSUE THREAD

**Issue by Regenhardt** [canton7/RestEase#155]
Can i somehow see the json payload actually being sent? Would be nice for debugging sometimes. and to tell people "Here this is exactly what I sent to your API".

**Comment by canton7** [comment]
I can think of a number of ways:

1. Use [Fiddler](https://www.telerik.com/fiddler): every API engineer's best friend
2. Use a [RequestModifier](https://github.com/canton7/RestEase#requestmodifier) and peek at the request
3. Copy [JsonRequestBodySerializer](https://github.com/canton7/RestEase/blob/6dcaa9f6b0f3b35451d25bb9cd1620c64d56284c/src/RestEase/JsonRequestBodySerializer.cs) into your code, [use it as the request body seriailzer](https://github.com/canton7/RestEase#serializing-request-bodies-requestbodyserializer), and put a breakpoint in it.
4. [Get symbols working](https://github.com/canton7/RestEase#installation) then put a breakpoint in RestEase's JsonRequestBodySerializer or Requester

Hope that helps!

**Comment by canton7** [comment]
Closing as no response
