### ISSUE TITLE
No content is written in PDFs uploaded using the instructions for multipart/form-data

### ISSUE THREAD

**Issue by sdg-sjb** [canton7/RestEase#157]
I have an objective to send a PDF file from one server to a REST API which handles some archiving. I am using .NET Core 3.1 and RestEase

I have a simple console app that runs at a certain time everyday. The relevant code is as follows:

```
using System;
using System.Linq;
using System.Threading.Tasks;
using RestEase;

namespace CandidateUploadFile
{
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                var apiClientBuilder = new ApiClientBuilder<ITestApi>();
                var api = apiClientBuilder.GetApi("https://localhost:5001");
                var candidate = await api.GetCandidateByEmailAddress("tester@aol.com");
                var fileName = "tester.pdf";
                var fileBytesToUpload = await FileHelper.GetBytesFromFile($@"./{fileName}");
                var result = await api.UploadCandidateFileAsync(fileBytesToUpload, candidate.Data.First().Id, fileName);
            }
            catch (Exception e)
            {
                System.Console.WriteLine(e);
            }
        }
    }
}
```
`apiClientBuilder` does some auth-header adding, and that's really it. I'm certain that bit isn't relevant.

`ITestApi` looks like this:

```
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Models;
using RestEase;

namespace CandidateUploadFile
{
    public interface ITestApi : IApi
    {
        [Get("v1/candidates/{candidateId}")]
        Task<Models.Response<Candidate>> GetCandidate([Path] string candidateId);

        [Get("v1/candidates")]
        Task<Models.Response<IEnumerable<Candidate>>> GetCandidateByEmailAddress([Query] string email);

        [Get("v1/candidates")]
        Task<Models.Response<IEnumerable<Candidate>>> GetCandidates();

        [Post("v1/candidates/{candidateId}/files?perform_as=327d4d21-5cb0-4bc7-95f5-ae43aabc2db7")]
        Task<string> UploadFileAsync([Path] string candidateId, [Body] HttpContent content);

        [Get("v1/users")]
        Task<Models.Response<IEnumerable<User>>> GetUsers();
    }
}
```
Per the docs, I'm using an extension method to handle the multipart/form-data piece, along with headers that are required by my API. That extension method looks like this:
```
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace CandidateUploadFile
{
    public static class ApiExtension
    {
        public static async Task<string> UploadCandidateFileAsync(this ITestApi api, byte[] data, string candidateId, string fileName)
        {
            var content = new MultipartFormDataContent();

            var fileContent = new ByteArrayContent(data);
            fileContent.Headers.ContentType = new MediaTypeHeaderValue("application/pdf");
            fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
            {
                Name = "file",
                FileName = fileName
            };

            content.Add(fileContent);

            return await api.UploadFileAsync(candidateId, content);
        }
    }
}
```

So what will happen when my console app executes is: I will get a successful response from the upload endpoint, and the file on the archive server gets created, but it's blank.

It may be important to know that this does not happen when I send, say, a .txt file. The .txt file will save with the expected content.

Not sure where to start on this one; it's not clear as to if this is a library issue or something else. Any insight would be helpful. Thank you!

**Comment by StefH** [comment]
I'm sure this helps or is comparable to your use-case, but here's how I did use it:

RestEaseApi interface method
``` cs
/// <summary>
/// uploads an image
/// </summary>
/// <param name="petId">ID of pet to update</param>
/// <param name="content">An extension method is generated to support the exact parameters.</param>
/// <param name="additionalMetadata">Additional Metadata</param>
[Post("/pet/{petId}/uploadImage")]
[Header("Content-Type", "application/octet-stream")]
Task<ApiResponse> UploadFileAsync([Path] long petId, [Body] HttpContent content, [Query] string additionalMetadata);
```

And my extension method:
``` cs
/// <summary>
/// uploads an image
/// </summary>
/// <param name="api">The Api</param>
/// <param name="petId">ID of pet to update</param>
/// <param name="additionalMetadata">Additional Metadata</param>
/// <param name="file">The content.</param>
public static Task<ApiResponse> UploadFileAsync(this IPetStoreOpenApi3Api api, long petId, string additionalMetadata, byte[] file)
{
    var content = new MultipartFormDataContent();

    var fileContent = new ByteArrayContent(file);
    content.Add(fileContent);

    return api.UploadFileAsync(petId, content, additionalMetadata);
}
```

Full examples can be found at https://github.com/StefH/RestEase-Client-Generator (https://github.com/canton7/RestEase/issues/143)

- https://github.com/StefH/RestEase-Client-Generator/blob/master/examples/RestEaseClientGeneratorConsoleApp/Examples/PetStoreOpenApi302/Api/IPetStoreOpenApi3Api.cs
- https://github.com/StefH/RestEase-Client-Generator/blob/master/examples/RestEaseClientGeneratorConsoleApp/Examples/PetStoreOpenApi302/Api/PetStoreOpenApi3ApiExtensions.cs
-

**Comment by canton7** [comment]
The starting point is to grab Fiddler and see what data's actually being uploaded. 

My other thought is, are you sure that a multipart upload is correct? You don't necessarily need that, [see these examples](https://github.com/canton7/RestEase#i-want-to-upload-a-file).

**Comment by sdg-sjb** [comment]
I should clarify: the API I'm calling is not my own; I'm restricted to follow their contract and expectations. They do require a multipart/form-data request [per their documentation](https://hire.lever.co/developer/documentation#upload-a-single-file)

@StefH Seems like the only differences between what you shared and mine is that you included a Content-Type header of `application/octet-stream`, and you did not include content-level headers like `ContentDisposition`. Without the content-disposition headers, I get a 400 from the API:

`"{\"code\":\"BadRequestError\",\"message\":\"File is not included in the request\"}"`

Also, I tried _leaving_ my content-level headers, but _adding_ `application/octet-stream` as a request-level header. I get the same 400 error when trying that

**Comment by canton7** [comment]
I think the next step is Fiddler, then. See what RestEase is putting out, and see what a successful upload looks like. Then play spot the difference.

Note that this is probably nothing to do with RestEase -- you're talking directly to HttpClient at this point.

**Comment by sdg-sjb** [comment]
Sure. So since the file I send via Postman results in a file with content, I'll compare the raw request gathered from Fiddler for Postman with the request submitted from my application, which results in a blank file. Body shortened for brevity:

Postman (good result):
```
POST https://api.lever.co/v1/candidates/<<removed>>/files?perform_as=<<removed>> HTTP/1.1
Authorization: Basic  << removed >>
User-Agent: PostmanRuntime/7.24.1
Accept: */*
Cache-Control: no-cache
Postman-Token: c4b2acb0-1255-4664-a8ba-26005f74a146
Host: api.lever.co
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------065702623202247563183338
Content-Length: 83219

----------------------------065702623202247563183338
Content-Disposition: form-data; name="file"; filename="tester.pdf"
Content-Type: application/pdf

%PDF-1.4
%����
501 0 obj
<</Linearized 1/L 83006/O 503/E 63657/N 1/T 72865/H [ 1076 225]>>
endobj
               
xref
501 39
0000000016 00000 n
0000001490 00000 n
0000001646 00000 n
 . . . .
 . . . .
trailer
<</Size 501/ID[<D99D73436DB5804C8C3D777F3763EE1A><9961447053C7064DAB15A51D2FE6A510>]>>
startxref
116
%%EOF

----------------------------065702623202247563183338--
```
Request fired from my code, using the extension method approach (blank file submitted; bad result):
```
POST https://api.lever.co/v1/candidates/<<removed>>/files?perform_as=<<removed>> HTTP/1.1
Host: api.lever.co
Authorization: Basic <<removed>>
Content-Type: multipart/form-data; boundary="b5c023cd-c936-4575-aac9-e1ab9821c03d"
Content-Length: 134392

--b5c023cd-c936-4575-aac9-e1ab9821c03d
Content-Type: application/pdf
Content-Disposition: form-data; name="file"; filename="tester.pdf"

%PDF-1.4
%����
501 0 obj
<</Linearized 1/L 83006/O 503/E 63657/N 1/T 72865/H [ 1076 225]>>
endobj
               
xref
501 39
0000000016 00000 n
0000001490 00000 n
0000001646 00000 n
 . . . .
 . . . .
trailer
<</Size 501/ID[<D99D73436DB5804C8C3D777F3763EE1A><9961447053C7064DAB15A51D2FE6A510>]>>
startxref
116
%%EOF

--b5c023cd-c936-4575-aac9-e1ab9821c03d--
```
It's easy to see the request-level headers are quite different, but I'm not sure any of those are relevant to having the file content successfully written, no? Would you have any recommendations on what to try in the code that would possibly influence the writing of the data to the file itself?

**Comment by StefH** [comment]
I see that the `Content-Length` is totally different?

**Comment by sdg-sjb** [comment]
Yes, I noticed that as well. I'm not sure what that's all about. I've shared my code to be transparent; it should be plain to see that I'm not doing anything more than adding the content the same way you demonstrated in your example

**Comment by canton7** [comment]
I'm very suspicious of that different content length as well.

If you use a text file, which you said works, do you get the same content length?

Is the actual uploaded contents different? I'd be surprised if there wasn't a difference somewhere. A hex editor should be able to do a binary diff.

How does your `FileHelper.GetBytesFromFile` work?

**Comment by sdg-sjb** [comment]
Hm, yes I am seeing discrepancies in VBinDiff.. I'm not sure what Postman is doing that my code isn't, that's the trouble.

The FileHelper code looks like this:
```
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace CandidateUploadFile
{
    public static class FileHelper
    {
        public static async Task<byte[]> GetBytesFromFile(string filePath)
        {
            var fileContents = "";
            using (var sr = new StreamReader(filePath))
            {
                fileContents = await sr.ReadToEndAsync();
            }

            var fileAsBytes = Encoding.Default.GetBytes(fileContents);
            
            return fileAsBytes;
        }
    }
}
```

**Comment by StefH** [comment]
Replace that code with just ‘File.ReadAllBytes(fileName);‘

**Comment by sdg-sjb** [comment]
Success! Thank you _so much_. I was at wit's end on this one..

Are you thinking it was due to me encoding with UTF-8?

**Comment by canton7** [comment]
You interpreted the bytes as utf-8 text, then turned them into utf-16 bytes (Encoding.Default is utf-16)

**Comment by sdg-sjb** [comment]
I guess the docs suggests otherwise:
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netcore-3.1#the-default-property-on-net-core

**Comment by canton7** [comment]
But, pdfs are binary and shouldn't be interpreted as text anyway.

Yes sorry, misremembered. System code page, which could be anything

**Comment by sdg-sjb** [comment]
I see.. That explains why .txt files were working and not pdfs.. Yikes, my bad. Foolish of me. Thank you for the help @StefH @canton7

**Comment by canton7** [comment]
(also, reading a file async does nothing unless it was opened as async. You'd also be better off grabbing a FileStream and using that as a SteamContent: then the whole thing doesn't have to be loaded into memory at once).

Glad you solved it!
