### ISSUE TITLE
RestEase.HttpClientFactory nuget package missing

### ISSUE THREAD

**Issue by chrisl-za** [canton7/RestEase#159]
Hi,

The [docs](https://github.com/canton7/RestEase#using-httpclientfactory) mention that we can set up RestEase to use HttpClientFactory by referencing the [RestEase.HttpClientFactory](https://www.nuget.org/packages/RestEase.HttpClientFactory) nuget package.

That package referenced in the docs is not listed or perhaps something else is wrong?  I'm getting a 404.  

![image](https://user-images.githubusercontent.com/66147670/85491023-10096700-b5d3-11ea-8d26-148e52e00ab2.png)

Could you please have a look?

Thanks!

**Comment by canton7** [comment]
You're a couple of days early: coming soon!

**Comment by canton7** [comment]
It's up now
