### ISSUE TITLE
1.5.0 release contains breaking changes

### ISSUE THREAD

**Issue by javicrespo** [canton7/RestEase#160]
Hello,

Is it possible that version 1.5.0 comes with breaking changes? 

We're using wildcard references for minor and patch versions:

` <PackageReference Include="RestEase" Version="1.*" />`

So, our build server has picked up RestEase 1.5.0 version as early as today. Our unit tests are now complaining because of this:

`---- System.TypeLoadException : Could not load type 'RestEase.Implementation.ImplementationBuilder' from assembly 'RestEase, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null'.`

Was that intended? We assumed this library was following semver. Even if so, we may have been too aggressive by taking latest minor/patch versions...

**Comment by canton7** [comment]
Nope, no breakage is intended. Are there any more details in your stack trace which might help narrow down the problem?

**Comment by javicrespo** [comment]
Happens when we call the implemenationbuilder

public class ClientFactory<TInterface> : IClientFactory<TInterface>
{
        static ClientFactory()
        {
            // Warm up: Force Generation of the Client code
            using var client = new HttpClient();
            ImplementationBuilder.Instance.CreateImplementation<TInterface>(new Requester(client));
        }

**Comment by canton7** [comment]
Ah, anything in the `Implementation` namespace isn't normally for public consumption, isn't considered part of the public API, and isn't covered by semver. I do have to expose stuff there for the generated implementation code to use unfortunately.

I'll make that clearer in the README.

`ImplementationBuilder` doesn't exist any more. The replacement type is `ImplementationFactory`.

**Comment by canton7** [comment]
Why not use `RestClient` to do your warm up? That's the public API which pretty much does exactly what you wrote.

**Comment by javicrespo** [comment]
Ok, makes sense :)
Yes, that's true, we could simply use the RestClient for the warmup, not sure why we used ImplementationBuilder for that...

**Comment by canton7** [comment]
(Re-opening as a reminder to improve the README here)
