### ISSUE TITLE
How to write reusable C# code to visit one URL

### ISSUE THREAD

**Issue by johngit2020** [canton7/RestEase#161]
Hello:
I have found an issue when I want to write reusable C# RestSharp code for visiting one URL:
https://www.betonline.ag/sportsbook/soccer/todaygames
First, I used Insomnia Rest Client Version: 2020.2.2; HTTP GET failed with error code: 1020.
Second, I tried with Postman Version 7.27.1, after I set up the following headers:
Accept, Accept-Language, Connection, User-Agent, then the HTTP GET works, I see OK 200 with a lot of data returned.
I can use the code generation by Postman to see the C# code, like the following:
`var client = new RestClient("https://www.betonline.ag/sportsbook/soccer/todaygames"); 
client.Timeout = -1; 
var request = new RestRequest(Method.GET); 
request.AddHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/apng,*/*;q=0.8"); 
request.AddHeader("Accept-Language", "en-GB"); 
request.AddHeader("Connection", "keep-alive"); 
client.UserAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36"; 
request.AddHeader("Cookie", "__cfduid=d0b759ddd2fd299d2f2c9de03c4b0fc831593630928; ASP.NET_SessionId=011tzj55pax0mteqwvyoy52j; KW_Search=domain=&kw=&HTTP_Refer=; UDeepLink=soccer/todaygames; THE_COOKIE=!8mJlp93nsBg0bsxPZwurU0T9hxdEzIjav0h+jNr3wz7WGGb3QX9sfA4aRlYR60ZxaQpPjWM/TK5nmlc=; __cf_bm=8428a48b248f93f0bcf0ce207c632a8dd4ea9bf8-1593882478-1800-AVbbpKBDcqxwlVhAJa+kDYiw2jOTOlW02R28g5sAp4Ga675L8j7ZywqzLlcBxCHJhj9vyrmCAHBI36cVdVupi5s=; __cfruid=4df47a91b423cd4a3d3d1de756d5e9e4657798c9-1593882478"); 
IRestResponse response = client.Execute(request); 
Console.WriteLine(response.Content);`
However, as I can see the cookies are specific for each different session.
If I want to write a C# reusable code to visit this URL, what I should do using RestEase?
Thanks,

**Comment by canton7** [comment]
I'm afraid I don't fully follow the question. If sending a request with a few specific headers, have you tried telling RestEase to send those headers?

If this is about cookies, then RestEase uses HttpClient under the hood, which should support cookies out of the box (see HttpClientHandler.UseCookies and Cookie Container).

**Comment by johngit2020** [comment]
Sorry, I didn't make my question clear.
I want to write a C# code, so that I can visit the same URL again and again.
The above code didn't work at all, if you run it in C# environment.
You can try this.
I didn't have any experience with RestEase yet, but if you can show me how to write a reusable C# code to visit the URL, that will be greatful.
Thanks,

**Comment by canton7** [comment]
If you keep calling the same method, it will keep sending the same request.

If the server decides to give you different responses at different times, you'll have to figure out why and what you can do about it.

The README had good instructions in it. Feel free to ask if you have specific questions which aren't addressed by the README.

If you're looking for general C# help, there are better places to ask I'm afraid.

**Comment by johngit2020** [comment]
Hi,
Usually, each time you visit one web site, if it is under cloudflare, cloudflare will give you some headers, and the HTTP GET will work.  I don't know how to receive and add the headers set by cloudfalre with RestEase.  If you can write some example code on how to get this specific URL, you can share with me.

**Comment by canton7** [comment]
I don't follow. You want to take headers which were added to the response by Cloudflare, and add them to the next request?

**Comment by canton7** [comment]
Closing as no response
