### ISSUE TITLE
Use x509 in RestEase requests

### ISSUE THREAD

**Issue by MikDal002** [canton7/RestEase#163]
Hello!
I'm looking for a solution for how to attach x509 to RestEase requests, especially in Xamarin.Forms. Is there any built-in solution?

**Comment by canton7** [comment]
RestEase is built in top of HttpClient, so whatever you'd use for HttpClient.

Looks like you can set HttpClientHandler.ClientCertitifates?

**Comment by canton7** [comment]
Closing as no response
