### ISSUE TITLE
Specifying a RequestModifier when using RestEase.HttpClientFactory

### ISSUE THREAD

**Issue by Wizhi** [canton7/RestEase#164]
I'm in need of a way of setting the `Authorization` header for requests, which [is handled quite neatly using a `RequestModifier`][rm]. This doesn't seem to be possible, however, if I'm registering my service using the [`RestEase.HttpClientFactory` abstraction][hcf], since this doesn't expose the same arguments as [`RestClient.For<T>`][rcf].

I'm not seeing any way of specifying a `RequestModifier` for clients, registered through any of [the `IServiceCollection.AddRestEaseClient<T>()` overloads][hcfe].

Am I missing some way of using the  `RestEase.HttpClientFactory` abstraction _with_ a custom `RequestModifier`?

If not, what would be the recommended approach to doing something similar?

[hcf]: https://github.com/canton7/RestEase#using-httpclientfactory
[rm]: https://github.com/canton7/RestEase#controlling-the-requests
[rcf]: https://github.com/canton7/RestEase/blob/master/src/RestEase/RestClient.cs#L137-L150
[hcfe]: https://github.com/canton7/RestEase/blob/master/src/RestEase.HttpClientFactory/HttpClientFactoryExtensions.cs

**Comment by canton7** [comment]
That's a fair request. That will be in the next version, but I can't say when that will be released.

In the meantime, you should be able to do:

```cs
services.AddRestEaseClient<T>(...).ConfigurePrimaryHttpMessageHandler(() => new ModifyingClientHttpHandler(requestModifier));
```

(Let me know if that doesn't work, as I'll need to change how I've implemented it!)
