### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by Piedone** [canton7/RestEase#165]
Would it be possible to set up GitHub sponsorship for the project, or some other way to financially contribute?

**Comment by canton7** [comment]
I've never thought it worth the bother of sorting out the tax aspect, in return for a few quid, to be honest.

If you want to give something, please push the equivalent of a beer or two towards Médecins sans frontières (or another worthy charity of your choice). I've got a fundraiser for MSF (for another project) [here](https://www.justgiving.com/fundraising/SyncTrayzor-MSF) if you'd rather.

Thanks!

**Comment by Piedone** [comment]
I see, thanks for the reply. We do have a charity [we continuously support](https://lombiq.com/blog/1000-masks-for-the-malteses-and-how-we-dealt-with-the-coronavirus-pandemic-until-now), the Hungarian Charity Service of the Order of Malta. Here we're specifically looking for suitable OSS projects to support.

**Comment by canton7** [comment]
(Just for the sake of the record, and anyone finding this issue, I've now enabled sponsorships for this repo. This is in no way a request or solicitation!)

**Comment by Piedone** [comment]
I'll check it out. PayPal Donate is not really suitable when donating as a company (since we need the proper paperwork, i.e. invoice), let's see if Ko-fi will work.

**Comment by Piedone** [comment]
Do I see correctly that it's not possible to do monthly recurring support but just one-time? Because it seems to me that you can enable monthly support on Ko-fi somehow.

**Comment by canton7** [comment]
You can, but it's $6/mo to enable it, which is excessive.

I've added liberapay to the list on the sponsor button, which allows recurring payments.

**Comment by Piedone** [comment]
Thanks! I had some questions for them about donating as a company.

**Comment by Piedone** [comment]
Just FYI, still working on this. GitHub Sponsors just works, as does Open Collective. Ko-fi is already a bit unusual in OSS but I made it work but now with liberapay it's yet another round of figuring out. The root of the issue is that as a company you can't just send money freely, there needs to be sufficient supporting documentation.

**Comment by Piedone** [comment]
Did it via Ko-fi in the end, in a single payment. Couldn't figure out liberapay.

**Comment by canton7** [comment]
WOW, thank you so much! That's incredible!

**Comment by Piedone** [comment]
Thank you for your work on RestEase :).
