### ISSUE TITLE
'Method 'GetById': unable to find a [Path("user")] property or parameter for the path placeholder '{user}''

### ISSUE THREAD

**Issue by jalil1408** [canton7/RestEase#166]
trying to pass constants to Get and Post attributes:

    public static class Routes 
    {
        public const string PREFIX = "/api/v1";
        public const string USER = PREFIX + "/users/{user}";
    }

    public interface IGitHubApi
    {
        [Get("/api/v1/users/{user}")]    =====> ok
        //[Get(Routes.USER)]             =====> 'Method 'Get': unable to find a [Path("user")] property or parameter for the path placeholder '{user}''

        Task<User> Get(string user); 
    }

**Comment by canton7** [comment]
I can't reproduce this. Are you sure that the const string is accessible from outside of the assembly (i.e. it's public, in a public class, not nested inside any non-public types)?

**Comment by jalil1408** [comment]
actually "'IGitHubApi doesn't look like a Refit interface" error was generated by Refit.

"unable to find a [Path("user")] property or parameter for the path placeholder '{user}''" was fixed just by changing the method to:
    [Get(Routes.USER)]
    Task<User> Get([Path] string user); 

I apologize for that.

**Comment by canton7** [comment]
No problem! You've got me thinking whether I can support non-public const strings now: that could be interesting.

Are there any remaining issues?

**Comment by jalil1408** [comment]
for now it works perfectly, thank you.

I just switched from Refit to RestEase because Refit does not support passing constants parameters from static classes to Get and Post attributes path.

**Comment by canton7** [comment]
No worries, hope you enjoy
