### ISSUE TITLE
Receiving headers from the server

### ISSUE THREAD

**Issue by mnkvsoft** [canton7/RestEase#168]
Good afternoon.
Is there some way to get the header from the server?

**Comment by canton7** [comment]
Make the method return a `HttpResponseMessage` or `Response<T>` (which has a `ResponseMessage` property which contains the `HttpResponseMessage`. From there you can get [`Headers`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.headers?view=netcore-3.1#System_Net_Http_HttpResponseMessage_Headers) and [`Content.Headers`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.content?view=netcore-3.1#System_Net_Http_HttpResponseMessage_Content)

**Comment by mnkvsoft** [comment]
Thanks for the quick response
