### ISSUE TITLE
How to enable TCP Keep Alive?

### ISSUE THREAD

**Issue by Segflow** [canton7/RestEase#169]
Is it possible to enable TCP Keep alive on the underlying socket used by the client?

**Comment by canton7** [comment]
RestEase is a wrapper over HttpClient. This sort of thing will be handled by HttpClient. If you can configure it on HttpClient, then do so, and pass that HttpClient to `new RestClient(...).For<T>()`

**Comment by canton7** [comment]
Closing as no response
