### ISSUE TITLE
Multiple method parameter attributes (decorators) for one method parameter.

### ISSUE THREAD

**Issue by SABEELKAZI** [canton7/RestEase#171]
Is it possible to use multiple method parameter attributes(decorators) for one method parameter ? The use case is that I am expecting a method parameter whose value must be set as both path parameter and as a header. And this parameter applies only to a single method.

**Comment by canton7** [comment]
It's not currently possible, but I don't see why it shouldn't be.

**Comment by canton7** [comment]
If you're interested in contributing, the relevant code is [here](https://github.com/canton7/RestEase/blob/f7efb7684b96ce9da4f55d52f7abfa94eb7c0340/src/Common/Implementation/ImplementationGenerator.cs#L265). You'll need to remove that test on `Count`, and change the `else if` change to just `ifs`. It's probably also worth thinking about whether to restrict which attributes can be applied together.
