### ISSUE TITLE
Proposal: Improving error handling with generic ApiException<TContent>

### ISSUE THREAD

**Issue by Chakrygin** [canton7/RestEase#172]
Hi!

Now, `ApiException` handling with RestEase has some difficulties:

1. Need to manually deserialize the response from `ApiException.Content`.
2. Need to manually check status codes in user code.
3. `AllowAnyStatusCodeAttribute` does not differentiate between client and server exceptions.

My proposal is to add a generic `ApiException<TContent>` type and a set of attributes to indicate the content type.

For example:

```
public class ApiException<TContent> : ApiException
{
    public new TContent Content { get; set; }
}
```

```
[StatusCode("5xx", ContentType = typeof(ServerErrorResponse))] // Throw ApiException<ServerErrorResponse> for any 5xx status code.
[StatusCode("4xx", Allow = true)] // Allow any 4xx status codes (equivalent for AllowAnyStatusCodeAttribute)
public interface IGreeterApi
{
    [Post("hello")]
    [StatusCode(HttpStatusCode.NotFound, ContentType = typeof(NameNotFoundResponse))] // Throw ApiException<NameNotFoundResponse> for 404 status code.
    public Task<HelloResponse> SayHello([Query] string name);
}
```

Then instead:

```
var greeter = RestClient.For<IGreeterApi>(httpClient);

try
{
    var response = greeter.SayHello(name: "World");
}
catch (ApiException ex)
    when (ex.StatusCode == HttpStatusCode.NotFound)
{
    var nameNotFoundResponse = JsonConvert.DeserializeObject<NameNotFoundResponse>(ex.Content);

    // ...
}
catch (ApiException ex)
    when (((int) ex.StatusCode) >= 500)
{
    var serverErrorResponse = JsonConvert.DeserializeObject<ServerErrorResponse>(ex.Content);

    // ...
}
catch (ApiException ex)
{
}
```

It will be possible to do it:

```
var greeter = RestClient.For<IGreeterApi>(httpClient);

try
{
    var response = greeter.SayHello(name: "World");
}
catch(ApiException<NameNotFoundResponse> ex)
{
    var nameNotFoundResponse = ex.Content;

    // ...
}
catch(ApiException<ServerErrorResponse> ex)
{
    var serverErrorResponse = ex.Content;

    // ...
}
catch (ApiException ex)
{
}
```

**Comment by canton7** [comment]
I'm open to adding a method to `ApiException` letting the user deserialize the content as a particular type, e.g. `ex.GetContent<NameNotFoundResponse()`. That means that your code becomes:

```cs
var greeter = RestClient.For<IGreeterApi>(httpClient);

try
{
    var response = greeter.SayHello(name: "World");
}
catch (ApiException ex)
    when (ex.StatusCode == HttpStatusCode.NotFound)
{
    var nameNotFoundResponse = ex.GetContent<NameNotFoundResponse>();

    // ...
}
catch (ApiException ex)
    when (((int) ex.StatusCode) >= 500)
{
    var serverErrorResponse = ex.GetContent<ServerErrorResponse>();

    // ...
}
catch (ApiException ex)
{
}
```

I'm also open to allowing a non-generic `Response` type, with a similar `GetContent<T>()` method.

I'm somewhat reluctant to add a complex attribute-based error-filtering system based only on one request. I'm also a bit reluctant to try and do automatic deserialization in error cases: if this deserialization happens to fail, you've got a failure as a result of handling a failure, which starts getting hard to explain clearly to the user. 

Of course you can always implement whatever you want as part of your own [`RequestModifier`](https://github.com/canton7/RestEase#requestmodifier) (you can fetch attributes from the `IRequestInfo` in `HttpRequestMessage.Properties`, see the link), or using [extension methods](https://github.com/canton7/RestEase#advanced-functionality-using-extension-methods).

**Comment by canton7** [comment]
Hi, any response?

**Comment by Chakrygin** [comment]
Hi,

Thanks for the answer!

1. The GetContent method will definitely make it easier to deal with errors (if it uses the same JsonSerializerSettings settings as the client)

2. I plan to look at RequestModifier to solve my problem.
