### ISSUE TITLE
RestEase.SourceGenerators does not play well with .editorconfig/StyleCop

### ISSUE THREAD

**Issue by VictorioBerra** [canton7/RestEase#174]
Added `RestEase.SourceGenerators` to my .NET 5 project, and the project no longer builds:

![image](https://user-images.githubusercontent.com/2934507/102521502-a1c1d080-405a-11eb-8d1d-8b8c7e3c68c7.png)

Editor Config: https://github.com/Dotnet-Boxed/Templates/blob/master/Source/ApiTemplate/.editorconfig

Maybe we need `// <auto-generated />` on the generated file or something? I am new with the Source Generators.

**Comment by canton7** [comment]
Looks like a bunch of those are StyleCop warnings, rather than being generated by the .editorconfig? IDE0053 looks like a .editorconfig one though.

Regardless, it looks like `// <auto-generated />` is the right approach: I'll try and get it in over the weekend.

**Comment by canton7** [comment]
In case it's not clear from the README, you can uninstall the source generator package and just use RestEase to work around this for now: you'll get any errors at runtime instead of compile time, but the functionality is the same.

**Comment by canton7** [comment]
Should be fixed in 1.5.2

**Comment by VictorioBerra** [comment]
Builds.

**Comment by canton7** [comment]
Thanks!
