### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Brrovko** [canton7/RestEase#176]
I use ResEasy for testing purposes. And I would like to reproduce the scenario manually if the test failed. Without opening IDE. Just looking logs in a CI\CD. Also, It is convenient to know what happened during the test run.
For this purpose, I need to see logs (console output may be): 1. Request URL, parameters, headers, cookie, body (if exist). 2. Response status code, headers, cookie, body.
Is it possible to add some switcher to turn on such logs?

**Comment by canton7** [comment]
You can write your own [`RequestModifier`}(https://github.com/canton7/RestEase#requestmodifier) which logs requests.

**Comment by canton7** [comment]
If you google "httpclient log all requests", there are plenty of things other people have written, from custom `HttpClientHandlers` to turning on the tracing present in HttpClient itself.

**Comment by canton7** [comment]
Closing as no response.
