### ISSUE TITLE
Use messagepack

### ISSUE THREAD

**Issue by matiassilioni** [canton7/RestEase#177]
Hey, I am actually using restease to conect different microservices. I love the simplest usability compared to other frameworks, attributes are the best. In order to improve performance between microservices I was thinking into change json serialization to messagepack. Both endpoints use .net5 asp.net core

How difficult would be? Where should I have to pay attention? Any advice is wellcome

**Comment by canton7** [comment]
Sure, should be easy enough. Start here: https://github.com/canton7/RestEase#deserializing-responses-responsedeserializer

**Comment by canton7** [comment]
Closing as no response.
