### ISSUE TITLE
Discuss supporting custom attributes

### ISSUE THREAD

**Issue by xljiulang** [canton7/RestEase#179]
What are the major differences between this project and refit? I found that I still don't support declaring a custom attribute. I want to handle the parameter value in my custom parameter attribute, such as using some sort of serialization or sorting its keyValue.
Maybe you can consider using the same design as [WebApiClient](https://github.com/dotnetcore/WebApiClient), and put the processing logic of request parameters into custom attributes.

**Comment by canton7** [comment]
> What are the major differences between this project and refit?

I used to have a section on that in the README, but I don't keep track of what new features Refit supports, so it got ever-more out of date, so I removed it.

> I found that I still don't support declaring a custom attribute.

I'm afraid I don't understand exactly what you're trying to do: can you give a more detailed example?

You can put your own attributes on methods, and then fetch them by querying `RequestInfo.MethodInfo` in a serializer/deserialize. Does that cover your use-case?

**Comment by xljiulang** [comment]
Thank you for coming to the discussion!

I need a custom `UrlEncodedAttribute` to implement logic directly in it to achieve the effect of `BodyAttribute(BodySerializationMethod.UrlEncoded)`

```
public interface IMeasurementProtocolApi
{
    [Post("collect")]
    Task CollectAsync([Body(BodySerializationMethod.UrlEncoded)] Dictionary<string, object> data);
}
```

When `UrlEncodedAttribute` put on the `data`  parameter，it's `OnRequestAsync` method will be called:
```
public class UrlEncodedAttribute : IApiParameterAttribute
{
    async Task IApiParameterAttribute.OnRequestAsync(ApiParameterContext context)
    {
        var keyValues = this.SerializeToKeyValues(context);
        await context.HttpContext.RequestMessage.AddFormFieldAsync(keyValues).ConfigureAwait(false);
    }

    protected virtual IEnumerable<KeyValue> SerializeToKeyValues(ApiParameterContext context)
    {
        return context.SerializeToKeyValues();
    }
}
```
Then I can implement subclasses of `UrlEncodedAttribute`, such as `SortUrlEncodedAttribute`:
```
public class SortUrlEncodedAttribute : UrlEncodedAttribute
{
    protected override IEnumerable<KeyValue> SerializeToKeyValues(ApiParameterContext context)
    {
        return base.SerializeToKeyValues(context).OrderBy(item => item.Key);
    }
}
```
Finally, these custom attributes can be reused on any parameter.

**Comment by xljiulang** [comment]
My custom parameter attribute can do anything I want, such as:
[SystemTextJsonBody], [JsonNetBody], [XmlBody], [GoogleProtobufBody], [Image2Base64StringBody],[UrlEncodedBody], [SortUrlEncodedBody], [SortAndSignedUrlEncodedBody]

**Comment by xljiulang** [comment]
These custom parameter attribute do not need the framework itself to understand what it is used for by its name, just need to execute the logic in it.

**Comment by canton7** [comment]
Can you give me an example of one of these attributes? What inputs would it take, and what outputs would it give? Would they be applied to parameters, methods, or both?

**Comment by canton7** [comment]
RestEase uses custom serializers to do that, e.g. [RequestQueryParamSerializer](https://github.com/canton7/RestEase#serializing-request-query-parameters-requestqueryparamserializer).

**Comment by canton7** [comment]
Closing as no response. Happy to reopen if you want to continue the conversation.
