### ISSUE TITLE
System.NullReferenceException in Requester.ConstructUri

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#18]
I am running into a null reference error when I move from simple test cases in NUnit into my actual application.  

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RestEase.Implementation.Requester.ConstructUri(String path, IRequestInfo requestInfo)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__23.MoveNext()
```

Here is the sample code that is throwing the error.  The odd part is -- this is 100% identical to what I am using in my NUnit test with the exception that this is running inside a Thread that is launched from a console application (it is a thread pool thread)

```
var httpClientApi = new HttpClient(new HttpClientHandler() { Credentials = new NetworkCredential(userName, password) })
{
	BaseAddress = new Uri($"https://localhost/Account/{_account.Id}/")
};

_restClientApis = new RestClient(httpClientApi)
					{
						RequestQueryParamSerializer = new CustomQueryParamSerializer(),
						ResponseDeserializer = new HybridResponseDeserializer(),
						RequestBodySerializer = new JsonRequestBodySerializer()
													{
														JsonSerializerSettings =
															new JsonSerializerSettings
																{
																	DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate,
																	Formatting = Formatting.Indented
																}
													}
					};

_itemApi = _restClientApis.For<IItemApi>();

var categoryResult = await _itemApi.GetCategoryAsync(); // null reference here
```

**Comment by ravensorb** [comment]
I found it -- looks like the IRequestQueryParamSerializer cannot return a null object from the SerializeQueryParam method?

**Comment by canton7** [comment]
Probably true. I should add checks to make sure that the serialised behave correctly. .

**Comment by ravensorb** [comment]
Thanks -- for now, I just return an empty dictionary.  You can close this if you want (unless you want to use it to track the change)

**Comment by canton7** [comment]
Fixes

**Comment by ravensorb** [comment]
Thanks.  Let me know when there is a new build and I will test

**Comment by canton7** [comment]
There'll be one on the AppVeyor feed now

**Comment by smiziara** [comment]
Im having the same error but im not initializing the RestClient with nothing especial, just the default RestClient.For<Interface>(Constructed http client).

**Comment by canton7** [comment]
@smiziara please open a new issue, provide all if the code needed to reproduce the exception, and paste the entire stack track.
