### ISSUE TITLE
Runtime exception with version 1.5.3

### ISSUE THREAD

**Issue by MaxDeg** [canton7/RestEase#182]
**Description**
Looks like adding a new option parameter to the ApiException constructor is a breaking change at runtime.
I think this is the change causing the issue:
https://github.com/canton7/RestEase/commit/15069ed7058384a35a9a30d937627903bc3800f6#diff-a899ea3b5e555a59489995a19c4baeb9d270f793b4c290022372e50c692cc3c6R67

`System.MissingMethodException : Method not found: 'Void RestEase.ApiException..ctor(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpResponseMessage, System.String)'.`

**To Reproduce**
Library A, referencing RestEase version 1.5.2 or lower
Library B, referencing RestEase version 1.5.3
Application C, reference libraries A and B

**Version Info**
 - RestEase version: 1.5.3
 - Target framework version: netcore3.1

**Additional Info**

**Comment by canton7** [comment]
My bad, fixed in v1.5.4

**Comment by MaxDeg** [comment]
Super fast thanks 🤩
