### ISSUE TITLE
Header is not updated on retry policy [RestEase+Polly combination]

### ISSUE THREAD

**Issue by ShykerBogdan** [canton7/RestEase#191]
Hi!
Really need some help to understand what am I doing wrong with my RestEase+Polly combination for reauthorization.

My policy looks like this:

```
var policy = Policy
            .HandleResult<HttpResponseMessage>(message => message.StatusCode == HttpStatusCode.Unauthorized)
            .RetryAsync(1, async (result, retryCount) =>
            {
                await _authorizeService.RefreshAccessToken();
                RestEaseClient.Token = _authorizeService.AccessToken;
            });
```
And IRestEaseClient looks like this:

```
public interface IRestEaseClient
{        
    [Header("X-Token")]
    string Token { get; set; }

    ["root")]
    Task SomeMethod();
    .................
}
```
When the token expires the breakpoint inside the policy retry function is hit, I successfully receive the new token, set its value to IRestEaseClient.Token header, but for some reason, the retry request goes with the old header value and I still get 401. The next request after this will go fine, without 401 and hitting the reauthorize policy code.

**Comment by canton7** [comment]
Presumably Polly is re-sending the `HttpRequestMessage` as-is? That `HttpRequestMessage` has already been constructed by RestEase, and RestEase is now out of the picture. You can change `RestEaseClient.Token` all you like, that won't have any effect until you call `SomeMethod` which constructs a new `HttpRequestMessage`.

At the very least, you need to update the X-Token header in your `HttpRequestMessage` with the new token. I might be tempted to go one step further, and handle the token entirely within an `HttpMessageHandler`.

**Comment by canton7** [comment]
(Converting to a discussion, per the issue template, as this isn't a bug)
