### ISSUE TITLE
ApiException class having only internal constructors makes unit testing difficult

### ISSUE THREAD

**Issue by ccp-ccollins** [canton7/RestEase#20]
In order to unit test that my code handled an error response correctly, I wanted to have a mock/fake implement the interface for my api, and simply throw an ApiException when the method in question is called.

Unfortunately, that's not possible with ApiException constructors being internal, so instead I had to research how to customize and override HttpClient and HttpMessageHandler to actually form a 500 status code response message, without actually making a request.  This was made made even more complicated by RestEase.Implementation.Request.ConstructUri insisting that the HttpClient have a valid BaseAddress (otherwise generating a NullReferenceException), even when the HttpClient itself would have worked fine without one.

I strongly recommend making the constructors for ApiException public to facilitate testing.  There needs to be an easier way to force an api call to fail (without actually using the network), for the purposes of unit testing.

**Comment by canton7** [comment]
> In order to unit test that my code handled an error response correctly, I wanted to have a mock/fake implement the interface for my api, and simply throw an ApiException when the method in question is calle

That's a valid request: I'm happy to make that change.

>  This was made made even more complicated by RestEase.Implementation.Request.ConstructUri insisting that the HttpClient have a valid BaseAddress (otherwise generating a NullReferenceException), even when the HttpClient itself would have worked fine without one.

That's incorrect behaviour: it should never throw an NRE.

**Comment by canton7** [comment]
Can you give me an example of a URI which HttpClient accepts, but which causes RestEase to throw an NRE, please?

**Comment by ccp-ccollins** [comment]
The problem is when its a custom HttpClient doesn't have (or need) a BaseAddress (i.e. set to null).  This causes an exception in RestEase when attempting to make a call to the API.  Minimal example as a .NET Core console project is attached.  [RestEaseNRE.zip](https://github.com/canton7/RestEase/files/564166/RestEaseNRE.zip)

**Comment by canton7** [comment]
Aah, a null BaseAddress, not an "invalid" one. Gotcha.

**Comment by canton7** [comment]
Released as v1.2.3.
