### ISSUE TITLE
The UseWithRestEaseClient<T> extension method does not allow to pass the RequestModifier

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#211]
**Description**
There is no `UseWithRestEaseClient<T>` extension method which also allows the RequestModifier, like:

``` c#
public static IHttpClientBuilder UseWithRestEaseClient<T>(
    this IHttpClientBuilder httpClientBuilder,
    Action<RestClient>? configurer = null,
    RequestModifier? requestModifier = null
)
    where T : class
{
    // ...
}
```

Can you please add this?

**Version Info**
 - RestEase version: 1.5.5
 - Target framework version: [e.g. net3.1]

**Comment by canton7** [comment]
The reason for this is that the `RequestModifier` is passed to a `ModifyingClientHttpHandler`, which is then configured as the primary HTTP handler using [`IHttpClientBuilder.ConfigurePrimaryHttpMessageHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler?view=dotnet-plat-ext-6.0). I therefore only do this is RestEase is the thing creating the `IHttpClientBuilder`: I don't want to overwrite someone else's primary HTTP message handler.

It would be possible to switch `ModifyingClientHttpHandler` to inherit from `DelegatingHandler`, and then we could use it with [`AddHttpMessageHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.addhttpmessagehandler?view=dotnet-plat-ext-6.0).
