### ISSUE TITLE
Custom RequestQueryParamSerializer -> Output parameters are automatically URL-encoded

### ISSUE THREAD

**Issue by vpellichero** [canton7/RestEase#219]
I have to deal with an API that expects such kind of query string:
`sort[0]=firstCriteria&sort[1]=secondCriteria`

In order to achieve it from an IEnumerable `[Query]` parameter, I created this custom `RequestQueryParamSerializer`:
```
public class MyCustomRequestQueryParamSerializer : RequestQueryParamSerializer
{
    /// <inheritdoc />
    public override IEnumerable<KeyValuePair<string, string?>> SerializeQueryParam<T>(string name, T value,
        RequestQueryParamSerializerInfo info)
    {
        if (value is null)
            return new KeyValuePair<string, string?>[0];

        return new KeyValuePair<string, string?>[] {
            new(name, ToStringHelper.ToString(value, info.Format, info.FormatProvider))
        };
    }

    /// <inheritdoc />
    public override IEnumerable<KeyValuePair<string, string?>> SerializeQueryCollectionParam<T>(string name, IEnumerable<T> values, RequestQueryParamSerializerInfo info)
    {
        // ReSharper disable once ConditionIsAlwaysTrueOrFalse
        if (values == null)
            yield break;

        var index = 0;
        foreach (var value in values)
        {
            if (value is not null)
                yield return new KeyValuePair<string, string?>(
                    $"{name}[{index++}]",
                    ToStringHelper.ToString(value, info.Format, info.FormatProvider));
        }
    }
}
```

But, after the query parameters are serialized, it seems that they are automatically url-encoded, and my query string becomes:
`sort%5B0%5D=firstCriteria&sort%5B1%5D=secondCriteria`

**Comment by canton7** [comment]
Is that a problem? `%5B` and `[` mean exactly the same thing in a URL. Strictly speaking, according to rfc3986, `[` and `]` are not valid in a query string:

```
   query       = *( pchar / "/" / "?" )

   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

Whereas `[` and `]` fall into `gen-delims`, which are part of `reserved`:

```
   gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   reserved    = gen-delims / sub-delims
```

From section 2.2:

>    URI producing applications should percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.  If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.

I don't see anything in section 3.4 about specifically allowing `[` and `]` there.

**Comment by canton7** [comment]
Glad you got it sorted!
