### ISSUE TITLE
Feature requests/proposals

### ISSUE THREAD

**Issue by fazouane-marouane** [canton7/RestEase#22]
Hi 😄 

I'd like to know your opinion on the following features:

1. Make instances of RestEase `IDisposable` when the provided interface is also `IDisposable`. The proposed semantics would be to dispose of the HttpClient. When the restease client is being disposed.
2. Accept an `IProgress<int>` and provide progress info to the caller. This can be interesting when downloading a big file using restease.

I can create a pullrequest but I wanted your preliminary input.
Thanks!

**Comment by canton7** [comment]
1. Sure, makes sense. Go for it! `IRequester` would be `IDisposable`, and `Requester` would dispose its `HttpClient`.
2. I'm not sure how you'd go about this, since HttpClient doesn't support reporting progress directly. You can wrap its response stream and read it bit-by-bit, but that's not going to work with `HttpResponseMessage` or `Response<T>` return types.

**Comment by canton7** [comment]
Right, I added `IDisposable` support.

Do you have an approach in mind for `IProgress<T>`?

**Comment by fazouane-marouane** [comment]
Hi,

Sorry this has totally slipped my mind. Thanks for supporting IDisposable!
For IProgress, I was thinking about something along the lines of this [Stackoverflow post](http://stackoverflow.com/questions/21169573/how-to-implement-progress-reporting-for-portable-httpclient).

**Comment by canton7** [comment]
Thinking about it a bit more, I don't think that it will work.

RestEast is primarily a REST API client. This comes with some assumptions, among them one that responses are small enough to be buffered in memory as strings, and deserialized to objects from memory. Responses this small don't need progress.

It does however support fetching larger resources, for the odd case where someone may need to. This is done by returning a `Task<HttpResponseMessage>`, where the user can call `.Content.CopyToAsync()` or similar, prompting an asynchronous fetch to disk. RestEase can't add progress to this case, as it doesn't get between the user and the `HttpResponseMessage`.

I think progress is better served by an extension method on `HttpContent` called `CopyToWithProgressAsync` or something, which takes a `Stream` and an `IProgress<T>`. This would be entirely independent of RestEase, and so I don't feel too comfortable about including it.

**Comment by fazouane-marouane** [comment]
I totally agree with you. How about doing some thing like the code bellow when restease should return a HttpResponse:
``ˋ{csharp}
    var response = await client.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, token);
```
Maybe we can introduce a flag to enable this behaviour?

**Comment by canton7** [comment]
[We do already](https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/Requester.cs#L308) ;)

**Comment by canton7** [comment]
Hmm. We currently send with `HttpCompletionOptions.ResponseContentRead`, so that the CancellationToken can cancel the reading of the body. I reckon it's probably fair to change this to `ResponseHeadersRead` if we're returning a `HttpResponseMessage`.

**Comment by canton7** [comment]
Right, change made.

**Comment by fazouane-marouane** [comment]
That's awesome! Thanks for your help! 😃

**Comment by canton7** [comment]
(Re-opening to remind me to make a release)
