### ISSUE TITLE
Request Modifier not reached when chained with ConfigurePrimaryHttpMessageHandler

### ISSUE THREAD

**Issue by stephenstroud** [canton7/RestEase#220]
Any ideas?  I need the ConfigurePrimaryHttpMessageHandler for self signed cert purposes.
```


            services.AddRestEaseClient<T>(baseAddress,
                client => { },
                
                 async (request, cancellationToken) => {                     
                    //do some request changes
                 })
                .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
                 {
                     ClientCertificateOptions = ClientCertificateOption.Manual,
                     ServerCertificateCustomValidationCallback =
                    (httpRequestMessage, cert, cetChain, policyErrors) => {
                        return true;
                    }
                 });



```

**Comment by stephenstroud** [comment]
This is kind of related to [](https://github.com/canton7/RestEase/issues/211)

Looks like the .ConfigurePrimaryHttpMessageHandler is configured after, but then how do I configure the cert?

**Comment by stephenstroud** [comment]
In the end I took inspiration in this [class ](https://github.com/canton7/RestEase/blob/a5a6514f54d7e41a5ed1acfcf6d46493402d8cea/src/RestEase/Implementation/ModifyingClientHttpHandler.cs) and made it work by introducing the ServerCertificateCustomValidationCallback within the constructor.

**Comment by canton7** [comment]
Yep it's the same issue. I'll get that fixed in the next release.

**Comment by canton7** [comment]
(this issue will get closed automatically when the release goes out)
