### ISSUE TITLE
async resquest  is not found

### ISSUE THREAD

**Issue by x-meta-hub** [canton7/RestEase#222]
**Description**
async resquest  is not found

**To Reproduce**
![image](https://user-images.githubusercontent.com/17669974/169199161-cb80eb66-e241-4c21-a548-8e0711f04468.png)

**Version Info**
 - RestEase version: [e.g. 1.5.0.0]
 - Target framework version: [e.g. net47]

**Comment by canton7** [comment]
I'm afraid there isn't enough information to understand your problem.

Please provide a full description of the error you're seeing, and all of the code needed to reproduce it.

**Comment by canton7** [comment]
Closing as no response
