### ISSUE TITLE
RestEase.SourceGenerator not using `*.g.cs` in generated source files.

### ISSUE THREAD

**Issue by brogdogg** [canton7/RestEase#226]
**Description**
A clear and concise description of what the bug is. Use screenshots as necessary.

I am utilizing the source generator to generate my API clients.  This unfortunately causes

`dotnet test --configuration Release --verbosity normal --collect:"XPlat Code Coverage"` 

To skip generating coverage for my library containing the interface with errors like:

```
[coverlet]Unable to instrument module: , pdb without local source files, RestEase_*.cs
```

Looking at coverlet they ignore all source generated files following Microsoft's recommendation, for example: `RestEase_*.g.cs`.

I know this is not necessarily a bug in this project, but was wondering if you wouldn't mind adding the `g.cs`?  I think it is being done [here](https://github.com/canton7/RestEase/blob/master/src/RestEase.SourceGenerator/Implementation/Processor.cs#L75).   If it is, I could open a PR to add it if you would like?

**To Reproduce**
Can use samples from your main ReadMe to generate.  Then run the:

`dotnet test --configuration Release --verbosity normal --collect:"XPlat Code Coverage"` 

**Version Info**
 - RestEase version: 1.5.5
 - Target framework version: net6.0

**Additional Info**

**Comment by canton7** [comment]
Sure, I don't see why not. I'm slightly surprised that the source generator machinary doesn't do this by default, but other MS SGs seem to have run into the same problem and are manually appending `.g` as a workaround.

**Comment by brogdogg** [comment]
Awesome @canton7, much appreciated on the quick turn around on that.  Tried it out today and works beautifully.

And I agree, seems weird the SG engine doesn't automatically handle that for ya.
