### ISSUE TITLE
Question: Extend the RestEaseGeneratedType ?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#235]
When using the RestEase.SourceGenerator, a internal class is generated: `internal class Implementation_1_ITestApi : global::Test.Net.Client.ITestApi`.

I want to extend this class like:
``` c#
public class MyClient : RestEaseGeneratedTypes.Implementation_1_ITestApi, ITestClient
{
    public Task<Result> DoSomethingAsync(string request, CancellationToken cancellationToken = default)
    {
        throw new System.NotImplementedException();
    }
}
```

But I encounter several issues:
- CS0060	Inconsistent accessibility: base class 'Implementation_1_ITestApi' is less accessible than class 'MyClient'
- CS7036	There is no argument given that corresponds to the required formal parameter 'requester' of 'Implementation_1_ITestApi.Implementation_1_ITestApi(IRequester)'

Do you have a solution or plan to change this behavior in a next version?

**Comment by canton7** [comment]
No, that is explicitely not supported. Even if you declare your subclass `internal` and give it the right constructor, there's an `[Obsolete]` attribute which will cause a compiler error. If you manage to hack your way around that, `RestClient.For` doesn't know anything about your subclass and won't instantiate it.

The name of a generated type is not stable (it may change from build to build), and the constructor syntax may change from release to release.

The supported way to add extra methods is using extension methods, [as documented here](https://github.com/canton7/RestEase#advanced-functionality-using-extension-methods).

**Comment by StefH** [comment]
Thank you.
