### ISSUE TITLE
Feature Request: Option to not throw exception on invalid HTTP Status Codes

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#25]
There are a lot of times when it is useful to simple check the status code of the response to do some logic rather than implement an exception handler, test for the status code, and then potentially re-setup the method.  It wold be very useful if there was a way (either at the Client level are at an indivdual interface level) to disable throwing an exception on Http Status result <> 200 which would then allow me to use 

```
var responseObject= await api.GetItemAsync();

if (!responseObject.ResponseMessage.IsSuccessStatusCode)
{
...
}
```

**Comment by canton7** [comment]
See https://github.com/canton7/RestEase/blob/master/README.md#response-status-codes

**Comment by ravensorb** [comment]
Should have know you already thought of this :)  Not sure why I couldn't find it when I search for info.  Closing the request now.

**Comment by canton7** [comment]
What were you searching for? Maybe there are some more keywords I should add to that section.
