### ISSUE TITLE
Extract ApiException creation from SendRequestAsync method

### ISSUE THREAD

**Issue by TobiasBreuer** [canton7/RestEase#257]
### Discussed in https://github.com/canton7/RestEase/discussions/256

<div type='discussions-op-text'>

<sup>Originally posted by **TobiasBreuer** April 13, 2023</sup>
@canton7 : Before creating a PR I would like to get your opinion on that topic.
....
</div>

In the end we want to extract the following parts of the `Requster` `SendRequestAsync` method to a seperate virtual method that can be customized:

````
if (!response.IsSuccessStatusCode && !requestInfo.AllowAnyStatusCode)
{
    var deserializer = new ApiExceptionContentDeserializer(this, response, requestInfo);
    throw await ApiException.CreateAsync(message, response, deserializer).ConfigureAwait(false);
}
```

**Comment by canton7** [comment]
That'll be out in 1.6.3 shortly!

**Comment by TobiasBreuer** [comment]
Awsome! Thanks!
However I noticed there is a small spelling mistake in `EnsureSuccessulResponseIfNecessary` maybe you want to add the missing 'f' in `Successul` before releasing the new version 😉

**Comment by canton7** [comment]
Right there we go: 1.6.4 out
