### ISSUE TITLE
Cannot install RestEase on a PCL with profile 259

### ISSUE THREAD

**Issue by cfl777** [canton7/RestEase#26]
Hi,
First to commend on this great library, really awesome. 

I initially tested this project on a shared project, for xamarin development, which has worked well (except for deserialization issues). I then wanted to use this library in a PCL, but I cannot get it to work. Does this library not support PCL? or are there other profiles I can try (already tried 111). 

`Could not install package 'RestEase 1.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 0	`

Thanks

**Comment by canton7** [comment]
RestEase requires netstandard 1.3, which is the lowest which provides things like reflection.

According to [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/articles/standard/library), PCL profile 259 is only compatible with netstandard 1.0. Looking at the table at the top, this is because Windows Phone Silverlight only supports netstandard 1.0.

So no, there are no PCL profiles which provide the tools that RestEase needs I'm afraid.

**Comment by canton7** [comment]
Although, it seems to be possible to get some bits of reflection working as low down as netstandard1.1... I'll have a play, but it might be a fair chunk of effort.

**Comment by canton7** [comment]
Right, so netstandard1.1 seems to work. That gives you profiles 7, 32, 44, 111, 151.

netstandard1.0 is a no-go, since HttpClient doesn't support it.

**Comment by canton7** [comment]
Right, v1.3.2 released on NuGet.

It won't work with 259, but should work with 111.

**Comment by cfl777** [comment]
@canton7  Thank you for the quick response!! 
Great, thank you for making the updates!

Will give it a try first thing tom, and report back.

**Comment by cfl777** [comment]
@canton7 
I have spent the whole day trying to get it installed. 

The package at least started to install, unlike before. However the installation got stuck when installing:
`System.Reflection.Emit.ILGeneration 4.0.1`

I have tried multiple profiles, 7, 24, 111. 

Please have a look, for more details:
http://stackoverflow.com/questions/42023709/reflection-emit-ilgeneration-fails-to-install#

It seems that the package cannot be used on PCL's, only 'standard' projects(I tested and it works) ?

**Comment by canton7** [comment]
Yeah, strange, I'm seeing the same. What's more strange is that profile 111 supports TypeBuilder natively, so installing System.Reflection.Emit.ILGeneration *should* just be a no-op. Looks like System.Reflection.Emit.ILGeneration is badly formed though.

**Comment by canton7** [comment]
Is there any for you to target the .NET Platform Standard instead?

**Comment by cfl777** [comment]
I agree doesn't seem badly formed. 

Unfortunately not at this point in time. I'm using MvvmCross as part of my framework, and they don't support it yet.

**Comment by canton7** [comment]
It's possible to use PCL libraries within a portable library targeting the .NET Platform Standard - use the `"imports"` directive in your project.json.

However that does mean you have to deal with the pain of .NET Core tooling, which is not something I'd wish on anyone...

**Comment by canton7** [comment]
Looks like it's technically possible for me to manually target PCL targets, as well

**Comment by canton7** [comment]
Hmm, it works if you target Profile49.

**Comment by cfl777** [comment]
I just tested, weirdly mine doesn't work though. 

It will be a problem for us to use that profile though, breaks other packages unfortunately :(

**Comment by canton7** [comment]
I had a play with trying to target PCL targets, but there's zero documentation and a good set of incomprehensible errors. If you can figure out how to make it work, I'm all ears.

Otherwise, I'm afraid RestEase probably isn't going to work for you then. Refit's good :smile:

**Comment by cfl777** [comment]
Hahaha agreed with the incomprehensible errors! :) Thank you though!! You have been the best library owner I've come across. 

I understand, seems like that's the case. Also have multiple issues with refit, but have some possible solutions to be tested.

**Comment by canton7** [comment]
I think PCLs are sufficiently ancient by this point that this issue can be closed.
