### ISSUE TITLE
Possibility to send body content (string) in POST request

### ISSUE THREAD

**Issue by chanhnn** [canton7/RestEase#262]
**Version Info**
 - RestEase version: 1.6.4
 - Target framework version: net7.0

**Description**
- my simple endpoint
        [HttpPost]
        [Route("sample-post")]
        public string SamplePost([FromBody] string input)
        {
            return "output";
        }

my simple interface
        [Post("sample-post")]
        [Header("Content-Type", "application/json")]
        Task<string> SamplePost([Body] string input = "");

But, when i execute, i'm getting exception

{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-db75eb062dbb6ccfac980a43cb789320-cce5159991e56e9d-00","errors":{"$":["'x' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."]}}

**Comment by canton7** [comment]
That should work fine. What string exactly are you passing to `SamplePost`?

**Comment by chanhnn** [comment]
Any string content, i always receive that exception

**Comment by canton7** [comment]
What was the exact string which you used to produce the error above? I want to know whether it starts with `x`

**Comment by chanhnn** [comment]
my sample code

* controller *
```c#
[ApiController]
    [Route("[controller]")]
    public class TodoController : ControllerBase
    {
        public TodoController()
        {
        }

        [HttpPost]
        [Route("sample-post")]
        public string SamplePost([FromBody] string input)
        {
            return "result";
        }
    }
```

* console app - test *

```c#
class Program
{
    public static void Main()
    {
        try
        {
            var api = RestClient.For<ISampleApi>("https://localhost:7119");

            api.SamplePost("input").GetAwaiter().GetResult();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}

[BasePath("Todo")]
public interface ISampleApi
{
    [Post("sample-post")]
    [Header("Content-Type", "application/json")]
    Task SamplePost([Body] string input);
}
```

**Comment by canton7** [comment]
And do you still get an error message containing `'x' is an invalid start of a value`? Or is it now `'i' is an invalid start of a value`?

**Comment by chanhnn** [comment]
yes, now exception

{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-d3745afa61e7411ebfd5823dc409d019-7595a4155875673e-00","errors":{"$":["'i' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."]}}

**Comment by canton7** [comment]
It looks like some piece of middleware in your asp.net stack doesn't like the fact that you've got a raw string in a body marked `application/json`.

I don't see any indication that RestEase is doing the wrong thing. I suspect you'll see the same error if you use postman or similar?

**Comment by chanhnn** [comment]
The sample api is created using the .net api template, and does not add any middleware at all

It's true that when I test the api with postman or insomnia: body/json, if I don't enter data (null), I get the same error (400 -> ok), if I enter empty data, it works normally.

If I change the body in the interface from a string type to a structured data type (class), the restease works ok.

**Comment by canton7** [comment]
What happens when you send a simple string using postman?

**Comment by chanhnn** [comment]
it works normally.

**Comment by canton7** [comment]
Use requestbin or similar. Make a request with RestEase and another with postman, and see what the difference is.

**Comment by canton7** [comment]
Hi, any update?

**Comment by canton7** [comment]
Closing as no response
