### ISSUE TITLE
Provide overload RestClient<T>.For(System.Uri)

### ISSUE THREAD

**Issue by LordMike** [canton7/RestEase#27]
Hi,

I just noticed that the `RestEase.RestClient.For<T>( .. );` method does not accept a `Uri` instance. When looking through the code for the variant accepting a `string`, I can see that internally `RestClient` is instantiated with a Uri. 

Could you provide an overload for this case? :)

Mike.

**Comment by canton7** [comment]
Released as 1.3.3
