### ISSUE TITLE
Cannot inherit Variable Interface Headers

### ISSUE THREAD

**Issue by diegoRodriguezAguila** [canton7/RestEase#3]
I have defined a common parent because I need authentication in almost all my api endpoints.
The parent endpoint looks like this:
```c#
public interface IAuthenticatedEndpoint
    {
        [Header("X-Api-Token")]
        string ApiToken { get; set; }
        [Header("X-Api-Username")]
        string ApiUsername { get; set; }
    }
```
And I inherit from it like this:
```c#
public interface IDevicesEndpoint : IAuthenticatedEndpoint
    {
        [Get("/devices")]
        Task<IList<Device>> GetAllDevices([QueryMap] IDictionary<string, object> filters);
    }
```

But when I try to call 
```c#
RestClient.For<IDevicesEndpoint>(BASE_URL, settings); 
```
it throws the following exception:
<i>
((System.TypeLoadException)e.InnerException).Message "Method 'get_ApiToken' in type 'RestEase.AutoGenerated.<>SGAM+Elfec+DataAccess+WebServices+ApiEndpoints+IDevicesEndpoint' from assembly 'RestEaseFactory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."
</i>

with the message:
<i>
Unable to create implementation for interface SGAM.Elfec.DataAccess.WebServices.ApiEndpoints.IDevicesEndpoint. Ensure that the interface is public,or add [assembly: InternalsVisibleTo(RestClient.FactoryAssemblyName)] to your AssemblyInfo.cs
</i>
Then, I've tried to do what it suggested (added the line on AssemblyInfo) but with the same result.

**Comment by canton7** [comment]
I hadn't even considered that someone might want to do that... Should be pretty easy to get that working. Copy/paste for now, and I'll get a new release out soon.

**Comment by diegoRodriguezAguila** [comment]
Thank you for the fast response, yes I'll have to just copy/paste the two properties on all endpoints for now. I'll be waiting for it, Nice library btw. :+1:

**Comment by canton7** [comment]
Thanks :smile: 

Righty, v1.0.2 should be on NuGet, which should fix this. Let me know if you have any other issues.

**Comment by diegoRodriguezAguila** [comment]
I've just tested it, but couldn't get it work. My parent interface also has static interface headers, I didn't put them on the first post, because I tought it wasn't relevant at all, because they were being correctly inherited. The exception I get is: 
```c# 
Child interface IAuthenticatedEndpoint may not have any [Header] attribtues
```
By reading your commit, I figured out it's intentional that children must not have static interface headers, but IAuthenticatedEndpoint is the parent interface not the child one.
It looks like this
```c#
[Header("Accept", "application/json")]
[Header("Content-Type", "application/json")]
public interface IAuthenticatedEndpoint
    {
        [Header("X-Api-Token")]
        string ApiToken { get; set; }
        [Header("X-Api-Username")]
        string ApiUsername { get; set; }
    }
```
I'm not sure if it was intended that way, but now I can only have in parent class or static interface headers or variable interface headers not both. 
Maybe I would need a workaround for this, because now, all my child interfaces need those 2 headers in each one, well almost it's better than repeating the 2 properties, but it doesn't feel DRY at all. 
Something I like of this library is that it's inspired in retrofit. I'm not sure about the complexity of making this work with inheritance, but in retrofit, for instance my interfaces I make a factory that instances them with the "global" headers in an request interceptor:
```java
RestAdapter.Builder().setRequestInterceptor(new RequestInterceptor() {
                    @Override
                    public void intercept(RequestFacade request) {
                        request.addHeader("Accept", "application/json");
                        request.addHeader("Content-Type", "application/json");
                        if (username != null && authToken != null) {
                            request.addHeader("X-Api-Username", username);
                            request.addHeader("X-Api-Token", authToken);
                        }).create();
```
So before sending each request it apllies the headers.

**Comment by canton7** [comment]
Ah, yeah those headers are relevant.

The reason I didn't want to support them is because it's unclear whether they apply just to methods defined in that interface, or to all methods in interfaces which inherit from that interface. I can imagine someone defining a bunch of separate interfaces, all with their own headers and methods, then combining them into one super API interface and being confused when the headers from all of the separate interfaces get mushed together.

In retrospect, I've already taken the stance that property headers are bunged together, so it's only consistent that I do the same for interface headers....

Re your "request interceptor" example, you can do exactly the same in RestEase: See https://github.com/canton7/RestEase#requestmodifier

**Comment by diegoRodriguezAguila** [comment]
Maybe, all children could inherit all parent's headers, variable and static ones, that would make sense because when you inherit each of them separately, that's their behavior.
In the other hand, I'm ashamed I didn't see the RestEase's requestmodifier, I could swear I had read all the docs. Thank you, that's all I need to get this working properly. The only minor problem is that I'm using a <b>JsonSerializerSettings</b> and there is no <b>For</b> method overload with <b>JsonSerializerSettings</b>  and <b>RequestModifier</b> at the same time, it doesn't matter at all, I can use the (HttpClient,JsonSerializerSettings) overload i guess. Maybe it would be good to have a builder like in Retrofit, that way there wouldn't be necessary to have a lot and different kinds of overloads.
I agree with you that isn't that necesary to add more complexity to inheritance headers, especially when we have the <a target="_blank" href = "https://github.com/canton7/RestEase#requestmodifier" >requestmodifier alternative</a>.

**Comment by canton7** [comment]
(Re-opening, because the current behaviour is inconsistent: interface headers and property headers have the same scope, but are treated differently).

**Comment by canton7** [comment]
Yeah, a builder might not be a bad shout!

**Comment by canton7** [comment]
Righty, v1.0.3 is out.

Headers on inherited interfaces are now allowed (and do what you expect for your use-case), and I've added the missing `RestClient.For` overloads.

I've resisted going down the builder route for now: it gets tricky, as you have dependencies between which parameters can be specified. E.g. if you pass a `HttpClient`, you can't pass a `RequestModifier`. Similarly if you pass a `RequestBodySerialzer`, there's no point in passing `JsonSerializerSettings`. A nice fluent interface would do it, but I'd have to maintain `RestClient.For` for backwards compatibility reasons anyway...
