### ISSUE TITLE
Migrate solution to .net core and VS 2017.

### ISSUE THREAD

**Issue by arkoc** [canton7/RestEase#33]
Migrate solution to .net core and VS17.

**Comment by canton7** [comment]
I did most of the migration a while back, but it's blocked by https://github.com/dotnet/cli/issues/5993.

**Comment by arkoc** [comment]
So sad...I really want to contribute to this awesome project. (But have no vs14 and .net core preview tools)

**Comment by canton7** [comment]
Right, I gave up on .NET 4.0 and finished the migration: it's in the develop branch.

**Comment by arkoc** [comment]
Awesome.

I will add this.
https://github.com/canton7/RestEase/issues/30

**Comment by canton7** [comment]
Closing, as I don't think it's worth leaving it open until the next release for visibility.
