### ISSUE TITLE
Bug with extra ? in URL on mono (Xamarin/Android/.NET Standard 1.1)

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/RestEase#35]
I am getting two ?'s in the URLs when building for NETSTANDARD (Xamarin Android) (WPF seemed to work fine.)  This causes REST HTTP calls to fail.

 - Potential Problem 1: `initialQueryString = "?" + rawQueryParameter;` (Requester.ConstructUri)
 - Potential Problem 2: `char separator = String.IsNullOrWhiteSpace(query) ? '?' : '&';` (QueryParamBuilder.Build)
 - Definite problem for me 3: `sb.Append(hasQuery ? '&' : '?');` (QueryHelpers.AddQueryString)

You can see ?'s are added in a few places and there is a different code path for .NET Framework, so I'm not sure how to best fix this aside from just forcing it to be right inside Requester.ConstructUri.

Temporary hackish fix in Requester.ConstructUri() that worked for me:  
```
var builtQuery = QueryParamBuilder.Build(initialQueryString, queryParams);
if (builtQuery != null && builtQuery.Length > 0 && builtQuery.StartsWith("?")) { builtQuery = builtQuery.Substring(1); }
uriBuilder.Query = builtQuery;
```

Reference on Stackoverflow: http://stackoverflow.com/a/11083456/208304

**Comment by canton7** [comment]
First things first, can you give a case which reproduces this issue? I have a [whole file](https://github.com/canton7/RestEase/blob/master/src/RestEaseUnitTests/RequesterTests/QueryParameterTests.cs) of tests around this, and all of them pass, so I'd like to know what exactly you're doing to cause this.

(I'm afraid I'm going to be fairly busy over the next couple of days)

**Comment by canton7** [comment]
Hi, any more info on this?

**Comment by jaredthirsk** [comment]
I will try to make a repro in the next 12h.   (Between this and another issue it's a blocking bug for me.)

**Comment by canton7** [comment]
> Between this and another issue

What other issue?

> it's a blocking bug for me

I'm pretty busy over the weekend and away on business next week, so if you want a speedy fix, a timely repo would be useful!

**Comment by jaredthirsk** [comment]
I am trying to reproduce on Windows and can't at the moment.  For Android, I am looking at the mono source code and see it adds a ? in the set_Query method.  So if you prefix it with ?, mono will double-prefix it: 

```
        public string Query {
            get {
                return m_query;
            }
            set {
                if (value == null) {
                    value = String.Empty;
                }
                if (value.Length > 0) {
                    value = '?' + value;
                }
                m_query = value;
                m_changed = true;
            }
        }

```

**Comment by jaredthirsk** [comment]
Aha!  Microsoft is now detecting whether you have a leading ? and won't duplicate it:

Decompiled by JustDecompile from C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.1\System.Private.Uri.dll
```
        public string Query
        {
            get
            {
                return this._query;
            }
            set
            {
                if (value == null)
                {
                    value = string.Empty;
                }
                if (value.Length > 0 && value[0] != '?')
                {
                    value = string.Concat("?", value);
                }
                this._query = value;
                this._changed = true;
            }
        }
```

**Comment by jaredthirsk** [comment]
So it seems the correct thing to do that works on both mono/Android and .NET Core 1.1.1 at least is to not feed the Query setter with a leading ?.  Make sense?

**Comment by canton7** [comment]
Yay BCL bugs! Thanks for figuring out what's going on.

**Comment by jaredthirsk** [comment]
FWIW I did a pull request to mono: https://github.com/mono/mono/pull/4724

**Comment by canton7** [comment]
Cool, that should fix it. I'll release soon.

**Comment by jaredthirsk** [comment]
Thanks!  
(BTW, Microsoft is going to just use the actual .NET source code for mono by the looks of it: 
 https://github.com/mono/mono/pull/4726/commits/795dcdbd629da0595fe3ac5bbc3577778292001f)

**Comment by jaredthirsk** [comment]
Did you look at this line in QueryHelpers.cs line 95?

`sb.Append(hasQuery ? '&' : '?');`

**Comment by canton7** [comment]
I did have a comment in there, but looks like I took it out.

QueryHelpers is imported verbatim from another package. I don't want to edit it.

**Comment by jaredthirsk** [comment]
Oops, I deleted my comment because I wanted to look deeper.

(I asked about QueryHelpers.cs line 95: `sb.Append(hasQuery ? '&' : '?');`)

**Comment by jaredthirsk** [comment]
I saw you put in a TrimStart('?') right before setting the Query property -- great!  Thanks for making this fix!
