### ISSUE TITLE
Support for IDisposable?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#37]
Your example code:
```c#
public interface IGitHubApi
{
  [Get("users/{userId}")]
  Task<User> GetUserAsync([Path] string userId);
}

IGitHubApi api = RestClient.For<IGitHubApi>("https://api.github.com");
User user = await api.GetUserAsync("canton7");
```

If I want to dispose the RestClient after use, is this possible like:
```c#
public interface IGitHubApi : IDisposable
{
  [Get("users/{userId}")]
  Task<User> GetUserAsync([Path] string userId);
}

using (IGitHubApi api = RestClient.For<IGitHubApi>("https://api.github.com"))
{
  User user = await api.GetUserAsync("canton7");
}
```

**Comment by canton7** [comment]
[See the README](https://github.com/canton7/RestEase#idisposable). Disposing the `IGitHubApi` will dispose the underlying HttpClient.

That said, you do not want to keep creating and disposing HttpClients. You want to create a HttpClient, and keep it around. There are plenty of blog posts on this topic.

**Comment by canton7** [comment]
Hi, does that answer your question?

**Comment by StefH** [comment]
Can you provide a link to some more details why httpclient should not be disposed/shortlived?

**Comment by canton7** [comment]
[Here](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) with [some discussion](https://www.reddit.com/r/csharp/comments/50hyfz/youre_using_httpclient_wrong_and_it_is/).

**Comment by StefH** [comment]
Thanks.
