### ISSUE TITLE
Multiple attributes (Post and Put) on same Method ?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#40]
Is it also possible to use the same method for both **Post** and **Put** ? Because the code below throws exception.

```c#
public interface ISomeApi
{
    [Post("users")]
    [Put("users")]
    Task CreateOrUpdateUserAsync([Body] User user);
}
```

**Comment by canton7** [comment]
No it isn't possible. If you called that method, should RestEase do a post or a put?

**Comment by StefH** [comment]
Indeed. Good point.
