### ISSUE TITLE
Question: is OAuth2 flow supported?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#41]
I was wondering if there is a default support or implementation for OAuth2 authentication flow ?

**Comment by canton7** [comment]
No explicit support. There's a [bit in the README](https://github.com/canton7/RestEase#requestmodifier) about using a RequestModifier to help with OAuth. I haven't tried to do OAuth with RestEase myself, so if there are features which could help, let me know your thoughts.

**Comment by StefH** [comment]
I'm currently trying out some example code, see https://github.com/StefH/RestEaseOAuth2Demo

(which is using https://github.com/StefH/WireMock.Net/tree/master/examples/WireMock.Net.ConsoleApplication to simulate OAuth2)

**Comment by canton7** [comment]
Cool, looks sensible.
