### ISSUE TITLE
Add AllowStatusCodeAttribute

### ISSUE THREAD

**Issue by roryprimrose** [canton7/RestEase#48]
I'm finding that the AllowAnyStatusCodeAttribute is a bit of a sledgehammer option. A common scenario I hit is to throw if there are any failures, but allow a 404 to be interpreted as a null. Under the current implementation I have to use AllowAnyStatusCode but this then takes away the benefit of throwing an exception on any other unexpected status code.

It would be great if there was also an AllowStatusCode attribute (allow multiple) that could target specific scenarios against a member.

For example:
```
        [Delete("customers/{id}")]
        [AllowStatusCode(HttpStatusCode.NotFound)]
        Task DeleteAsync([Path("id")] string id, CancellationToken cancellationToken = default(CancellationToken));
```

This would allow for the expected outcomes as well as 404, but throw on anything else.

Thoughts?

**Comment by canton7** [comment]
I'm a bit wary of adding extra complexity to support niche edge-cases, especially where the same can be achieved in a couple of lines of code.

I think this might be a bit of a rabbit hole. `[AllowStatusCode(HttpStatusCode.NotFound)]` implies that *only* 404 is permitted (and any 3xx status code is forbidden). Sure that could be improved by e.g. `[AllowNontSuccessStatusCode(HttpStatusCode.NotFound)]`, but then we're going to need to be able to specify multiple status codes, and status code ranges, and allow any 4xx status code, etc... The complexity increases, and the ability of someone to read a RestEase interface and figure out what's going on decreases.

My preferred approach would be to write an [extension method](https://github.com/canton7/RestEase#wrapping-other-methods) which does the status code checking / throwing you want.

**Comment by roryprimrose** [comment]
Yep, I understand. I am already using an extension method to convert a model into a dictionary for an API that only supports form post fields.

As far as I can tell even an extension method wouldn't support this case because the status code is handled at a lower level. Presumably I would have to implement my own IRequester to support this scenario.

**Comment by canton7** [comment]
You could do something like (untested):


```csharp
public interface IMyApi
{
    [AllowAnyStatusCode]
    [Delete("customers/{id}")]
    Task<HttpResponseMessage> DeleteImplAsync([Path("id")] string id, CancellationToken cancellationToken = default(CancellationToken))
}

public static class MyApiExtensions
{
    public static async Task DeleteAsync(this IMyApi api, string id, CancellationToken cancellationToken = default(CancellationToken)
    {
        var response = await api.DeleteImplAsync(id, cancellationToken);
        if (response.StatusCode != HttpStatusCode.NotFound)
            response.EnsureSuccessStatusCode();
    }
}

**Comment by canton7** [comment]
I keep toying with the idea of allowing abstract classes instead of interfaces, which would allow you to do something like:

```csharp
public abstract class MyApi
{
    [AllowAnyStatusCode]
    [Delete("customers/{id}")]
    protected abstract Task<HttpResponseMessage> DeleteImplAsync([Path("id")] string id, CancellationToken cancellationToken = default(CancellationToken));

    public async Task DeleteAsync(string id, CancellationToken cancellationToken = default(CancellationToken)
    {
        var response = await this.DeleteImplAsync(id, cancellationToken);
        if (response.StatusCode != HttpStatusCode.NotFound)
            response.EnsureSuccessStatusCode();
    }
}
```

... but I haven't yet evaluated how hard it would be.

**Comment by roryprimrose** [comment]
I get where you are going with this but it really makes the interface design dirty. Clean interfaces was one of the reasons I really like working with RestEase. Abstract classes, hmm, maybe but that isn't as nice either. 

Could there be another extensibility point that can be manged via RestClient? That way you don't have to dirty up your implementation and I don't have to dirty up my API design. I control how RestClient is used so I could then provide custom implementation for handling (or passing through) the HTTP response.

**Comment by canton7** [comment]
> Could there be another extensibility point that can be manged via RestClient?

`IRequester`.

**Comment by roryprimrose** [comment]
Thanks, I'll take a look.
