### ISSUE TITLE
Culture during serialization

### ISSUE THREAD

**Issue by Kemyke** [canton7/RestEase#49]
Is it possible to set the culture during serialization, i couldn't find any option for that?
I found only the Format string parameter of the QueryAttribute but it is not possible to control the separator characters with format string. 
The serialization culture should be adjustable separately from thread culture.

**Comment by canton7** [comment]
What do you mean by "separation characters"?

**Comment by StefH** [comment]
I guess that the `.` and the `,`.

**Comment by canton7** [comment]
Oh! You're talking about formatting floating point numbers. That wasn't clear. 

No, there is no built-in way to do this. You can't specify a CultureInfo in an attribute anyway.. 

You could instead pass a string and call ToString yourself, or you could write an IRequestQueryParamSerializer. If you do the latter, you could abuse the Format parameter to pass the name if the culture, if you wanted.

**Comment by Kemyke** [comment]
Thanks for the reply. Now as we control the client and the server side we can modify the serialization. So we are happy with that. But i think it would be possible to support a config variable which can be loaded by RestEase and it could override the thread culture. Just an idea.

**Comment by canton7** [comment]
Writing your own IRequestQueryParamSerializer has nothing to do with whether you control the server. Your IRequestQueryParamSerializer implementation would do exactly the same thing as the default IRequestQueryParamSerializer (which just calls ToString()), except that it would pass a culture. The server would not know the difference. 

Sure I'll consider adding it to the config. The tricky thing, as always, will be maintaining backwards compatibility on the serialisers and deserialisers.

**Comment by canton7** [comment]
I *think* I caught everything there...
