### ISSUE TITLE
Consider using Microsoft.Bcl to create a 4.0 Port of Library

### ISSUE THREAD

**Issue by agerace23** [canton7/RestEase#5]
This library is a great. However I wish it had a .Net 4.0 version so that I could use it support Legacy Applications. Using the Microsoft.Bcl and Microsoft.Bcl.Async libraries I think this could be easily done.

**Comment by canton7** [comment]
HttpClient is 4.5 as well though. I'm looking at making a pcl, so there may be scope for supporting 4.0 with the help of copious nuget packages...

**Comment by agerace23** [comment]
Thanks for the quick response. Greatly appreciated. A pcl would be wonderful. HttpClient can be used with Microsoft.Net.Http nuget library. The only thing I haven't been able to find a Bcl for is IReadOnlyList. I have it building currently but failing some UnitTest. The library is working in a limited "Get" Request scenario I am currently using it in.

**Comment by canton7** [comment]
Aah cool. I've got some free time tomorrow, so i'll have a look then.

**Comment by canton7** [comment]
Right, that should be set up. Mind testing for me quickly before I push it up to NuGet? Grab version 1.0.5.74 from the NuGet feed https://ci.appveyor.com/nuget/restease . Thanks!

**Comment by agerace23** [comment]
Awesome man! You made my day. It is working when installing into a 4.0 or a 4.5 library. Disclaimer I am only using for Get Request with Path and Query variables currently. I will watch for an update on the main NuGet feed. I will be sharing this library with my team. I really appreciate the fast support!

**Comment by canton7** [comment]
Cool, so long as it compiles and creates the interface implementation, anything else is in the hands of the Microsoft BCL NuGet packages, which is a risk I'm happy to take.

Just to make sure: it didn't try and install anything about from Json.NET as a dependency when you installed it into a .NET 4.5 project? I had some trouble with that, but pretty sure I nailed it in the end.

**Comment by agerace23** [comment]
This is what I get when I install it in a 4.0 Project:

  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net40" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net40" />
  <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="net40" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net40" />
  <package id="Newtonsoft.Json" version="6.0.5" targetFramework="net40" />
  <package id="RestEase" version="1.0.5.75" targetFramework="net40" />

And into a 4.5 Project:
  <package id="Newtonsoft.Json" version="6.0.5" targetFramework="net452" />
  <package id="RestEase" version="1.0.5.75" targetFramework="net452" />

So looks like it is targeting the right stuff.

**Comment by agerace23** [comment]
Btw, if you are ever interested if you upload to NuGet as prerelease just put a -pre (or -anything) after the version and it will be in the prerelease feed for NuGet.

**Comment by canton7** [comment]
Awesome, 1.0.6 is up on NuGet! Thanks for your help :smile:

**Comment by agerace23** [comment]
No thank you man.

**Comment by canton7** [comment]
Yeah, the hangup is that adding '-pre' to the version doesn't really tie in with how I've got AppVeyor set up: it doesn't like non-integer versions, and I've got the versioning tied into `AssemblyVersion` which doesn't like them either. Besides, I get the AppVeyor feed "for free" with all of the builds on it, so it's less effort to use that than to push things up to NuGet.
