### ISSUE TITLE
Is Newtonsoft.Json >= 9.0.1 needed?

### ISSUE THREAD

**Issue by Piedone** [canton7/RestEase#52]
First of all, great library! Secondly, in my project for some obscure reason I need to use v7.0.1 of Newtonsoft.Json. I see that with RestEase 1.4.0 the required version of Newtonsoft.Json was upped to 9.0.1

Is indeed this version that is required for RestEase at the minimum or could the latest RestEase work with some older JSON.NET too?

**Comment by canton7** [comment]
To be honest, I'm not sure. I need very little of what json.net offers, so it may be that 7.x works fine, too.

**Comment by Piedone** [comment]
Thank you for the quick answer. If I'd to contribute a little change of modifying the minimum required version how can I test for any incompatibilities apart from obvious build errors? Would running the unit tests be enough?

**Comment by canton7** [comment]
I can't remember whether the unit tests go as far as exercising the default serializers / deserializers (which use json.net). It would probably be good to have some simple tests for JsonResponseDeserializer, JsonRequestBodySerializer, and JsonRequestQueryParamSerializer.

**Comment by StefH** [comment]
You could also investigate if it's even possible to lower the dependencies on json.net even more by referring to version **6.0.8**. However, I don't think this version is supported for `netstandard 1.3` so for that you need to use a higher version.

**Comment by canton7** [comment]
What's special about 6.0.8, in particular?

**Comment by canton7** [comment]
I've set it to 6.0.1. Let me know why 6.0.8 is special if it matters.

**Comment by StefH** [comment]
Not really special. It's just that the 6.08 version was mostly used by some other dependecies in the past. And it is the latest version 6 package.

**Comment by canton7** [comment]
Cool, thanks for letting me know.

**Comment by Piedone** [comment]
Wow that's nice, thank you.
