### ISSUE TITLE
.Net native compilation error

### ISSUE THREAD

**Issue by RaminMT** [canton7/RestEase#55]
Hi, I'm using this lib on my UWP project but when I run the app on Release mode I get following exception due to creating a new object but I don't know why
`Method 'AssemblyBuilder.DefineDynamicAssembly(AssemblyName, AssemblyBuilderAccess)' was not included in compilation, but was referenced in ImplementationBuilder..ctor(). There may have been a missing assembly.`

**Comment by canton7** [comment]
You won't be able to use RestEase with .NET Native.

RestEase creates new types at runtime. NET Native won't support this.

**Comment by RaminMT** [comment]
So what should I do?!
You mean I can't package my app?!

**Comment by canton7** [comment]
Hmm, a quick google suggests it can be worked around. What is the exception type, exactly?

**Comment by canton7** [comment]
Try adding something like this to your default.rd.xml?

```xml
<Namespace Name="System.Reflection.Emit" Dynamic="Required All"/>
```

**Comment by RaminMT** [comment]
The exception type is System.Exception & exception message is what I posted in first post with nothing special more.
I tried the code, added it to the file under `<Application>` in `<Directives>` but again same error.

**Comment by canton7** [comment]
Are you sure? That would be very unusual. Can you post the entire exception details, including the stack trace, etc?

**Comment by RaminMT** [comment]
```
System.Exception: Method 'AssemblyBuilder.DefineDynamicAssembly(AssemblyName, AssemblyBuilderAccess)' was not included in compilation, but was referenced in ImplementationBuilder..ctor(). There may have been a missing assembly.
   at RestEase.RestClient.For[T]()
   at MyProject.ViewModel.ViewModelBase..ctor() in C:\fakepath\ViewModel\ViewModelBase.cs:line 17
   at MyProject.ViewModel.MainPageVM..ctor() in C:\fakepath\ViewModel\MainPageVM.cs:line 120
   at MyProject.MyProject_XamlTypeInfo.XamlTypeInfoProvider.Activate_132_MainPageVM() in C:\fakepath\obj\x64\Release\XamlTypeInfo.g.cs:line 606
   at Template10.Template10__Library__XamlTypeInfo.XamlUserType.ActivateInstance()
   at __Interop.ReverseComStubs.Stub_7(Object __this, Void** unsafe___value__retval, IntPtr __methodPtr) in C:\fakepath\obj\x64\Release\ilc\intermediate\MyProject.McgInterop\SharedStubs.g.cs:line 26428
```

**Comment by StefH** [comment]
For creating dynamic classes, you can also take a look at:

https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicClassFactory.cs

or

https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/ClassFactory.cs

**Comment by canton7** [comment]
@StefH How does that help? That still uses an AssemblyBuilder.

**Comment by canton7** [comment]
From some googling around, it looks like System.Reflection.Emit is simply not available in UWP. Despite UWP claiming to implement the .NET Standard. Yay.

Until/unless I get something together with Fody / source generators, I'm afraid you're out of luck here. Refit is good :)

**Comment by RaminMT** [comment]
Thanks man <3
Actually I was Refit user there also I've got another problem that they suggest me to use RestEase 😆

**Comment by canton7** [comment]
Haha! I've been recommending them for a while, interesting to see they're recommending me now...

**Comment by RaminMT** [comment]
@canton7 
Hi,
The new VS 2017 (V15.4) & UWP fall creators SDK seems got some good news, could you please checkout [here](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.3.26730.16)? (In the middle of page, .NET Standard 2.0 Support section)

**Comment by canton7** [comment]
So far as I can see, that only adds support for .NET Standard 2.0? There's nothing about supporting things like TypeBuilder in .NET Native?
