### ISSUE TITLE
Support for Stream response

### ISSUE THREAD

**Issue by MaxDeg** [canton7/RestEase#56]
Is it possible to support stream response on interface? (I can make the PR)
For now this kind of method is not supported
```csharp
public interface I1
{
    [Get("/{id}")]
    Task<Stream> GetContent(string id);
}
```
Could be useful to be able to return directly the response stream without the necessity of exposing the HttpResponseMessage in the interface.

What do you think?

**Comment by canton7** [comment]
I'm in favour of the concept, but hold off on the implementation for now.

My worry is that someone might be deserializing to a stream type in a custom deserializer, and we'll go and break them. I've got plans to remove the special handling for string vs HttpResponseMessage vs custom type, and instead put this knowledge in the default deserializer. That will also mean that we can add support for Stream to the default deserializing without breaking people who have their own deserializer. It also means that this will be easier to implement - no hacking about with IL required.

**Comment by MaxDeg** [comment]
Sure.
I completely agree and love the idea. I first checked in the deserializer but it is not async and take the content as a string.
Do you have any timing about this big change? Any help wanted?

**Comment by canton7** [comment]
A recent change was to move to a base class for the deserializer. This means we can change the signature to be async and drop that string, while keeping backwards compatibility.

Sure, go for it if you want, but be prepared that I might be changing my mind as we work this out, and that might waste your time. 

First step is adding a new method to the ResponseDeserializer, and obseleting the existing method (which is annoying, as I'd only *just* introduced it....). I'm not yet sure whether the ResponseDeserializer itself wants to have logic to distinguish between stream/string/other, or whether we want to force all custom deserializers to duplicate this logic. Or whether we want a TextBasedResponseDeserializer which handles the string/stream/custom object distinction, and recommend that people subclass this if they want to write a custom deserializer, or...

**Comment by canton7** [comment]
... that will also solve #19, for the record.

**Comment by MaxDeg** [comment]
Maybe we could have something like a ResponseDeserializerFactory
```csharp
public class ResponseDeserializerFactory
{
  public ResponseDeserializer For<T>() { ... }
}
```
Each ResponseDeserializer would handle a number of types and the default one is the JsonResponseDeserializer which is called if no other provider is found

**Comment by canton7** [comment]
Then you need a system for people to register their deserializer, and a way for one type of deserializer to override another type. All of which is quite complicated, and none of which is backwards compatible.

**Comment by MaxDeg** [comment]
indeed

**Comment by MaxDeg** [comment]
I made a first try yesterday. I tried to reduce the breaking change but didn't find a solution for Response<T>. And don't like the defaultresponse deserializer

**Comment by canton7** [comment]
Thanks. I had a quick glance, but I'll try and make time for a proper look this lunch time.

**Comment by canton7** [comment]
I had some time this evening, so had a quick first attempt: https://github.com/canton7/RestEase/tree/feature/deserializer . Some tests fail, some obsolete warnings left, etc.

Dunno whether it works. I think I'm backing away from the "TextBasedResponseDeserializer" approach - people are going to have to update their deserializers to avoid the obsolete warning, so that's the time where they'll realise they might have to handle "string" especially.

**Comment by MaxDeg** [comment]
Looks good :)
We need to find a better name than JsonResponseDeserializer if this class handle also stream type :)

By the way any reason why you use a Func<Task<T>> instead of a Lazy<Task<T>> here?https://github.com/canton7/RestEase/blob/feature/deserializer/src/RestEase/Response.cs#L13

**Comment by canton7** [comment]
Fair point, a Lazy would work well. I'm also not happy with how the non-async methods suddenly became blocking in the `Response<T>`, so more work to be done there....

I think JsonResponseDeserializer is fine. It deserializes JSON responses, and passes through things which aren't JSON. A bare string isn't valid JSON, and so it makes sense that it's the JSON deserializer which decides not to try and deserialize it.

**Comment by canton7** [comment]
Thinking about it, why do you want to get the response as a stream? If you're planning on streaming the response to disk, then that's not going to work as things stand: we pass HttpCompletionOption.ResponseContentRead (except when returning a void response or a HttpResponseMessage), so that the CancellationToken the user passes will cancel the whole request. Therefore the entire response will be read by the time you get the stream. We will need to treat Stream separately to avoid this, which means we can't just push it down to the ResponseDeserializer.

**Comment by MaxDeg** [comment]
It's indeed to get stream from a kind of file storage api. I understand your point, We indeed need to handle it the same way as HttpResponseMessage

**Comment by canton7** [comment]
Apologies for the delay. That's in 1.4.3.

**Comment by MaxDeg** [comment]
Thanks a lot :)
