### ISSUE TITLE
Readme: make more clear whether iOS supported

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/RestEase#58]
Can you make this clearer?
Readme says "PCL profiles 7, 32, 44, 111, 151, excluding iOS" -- does that mean it works on those profiles except on iOS, or does it mean "except iOS" apply to the entire library?  And if it doesn't work on iOS, is it because of AOT?

I am using this on the current release of Xamarin Android, was wondering if I could use it on Xamarin iOS as well.

-Thanks

**Comment by canton7** [comment]
I don't understand what you mean by "or does it mean "except iOS" apply to the entire library". It's not valid English.

RestEase doesn't work on iOS, at all. iOS doesn't let you generate code at runtime.

**Comment by jaredthirsk** [comment]
Sorry, I meant to say  "...or does it mean the phrase 'excluding iOS' applies to the entire library?"

I am not very familiar with PCL profiles and largely managed to avoid them, so that may be partly why this seems ambiguous to me:

> .NET Framework 4.5 and higher and .NET Core (.NET Platform Standard 1.1, PCL profiles 7, 32, 44, 111, 151, excluding iOS)

Xamarin runs on mono, which is neither .NET Framework nor .NET Core, but more similar to .NET Framework.  From the way this sentence is written, I was not sure if the 'excluding iOS' part applied to just the PCL profile, or .NET Core, or the whole situation including mono.

In any case, you've answered my question -- thanks.  You can close this issue if you like.

**Comment by canton7** [comment]
Aha, I see. The sentence is meant to say "RestEase has two targets: .NET Framework and .NET Core. It targets .NET Core by targeting the .NET Standard 1.1, which includes PCL profiles 7, 32, 44, 111, 151. It does not support iOS".

Mono implements the .NET Standard (see the table [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)), as does the .NET Framework. 

I'll reword it.

**Comment by jaredthirsk** [comment]
That sounds great, thanks.  (To be more pedantic/specific, the platforms I use on iOS and Android are Xamarin.Android and Xaamrin.iOS (which use a mono runtime.))

**Comment by jaredthirsk** [comment]
Thinking out loud... I wonder if there is a way to use roslyn to generate at compile time the code necessary for iOS.  (I just made my first automatic C# code generator so it has got me thinking.)

**Comment by canton7** [comment]
Fody would be the way to go. It's on the roadmap, but it's a lot of work.
