### ISSUE TITLE
Documentation should show Production implemtation

### ISSUE THREAD

**Issue by Skylertodd** [canton7/RestEase#59]
After reviewing your quick start  documentation I was under the assumption that there was no need for a singleton implementation to manage the connections.  After testing this via a web application it was apparent that we were experiencing issues due to RestEase being unable to get an external connection.

Something like this would help explain my issues.

```
public class Startup
{	
	public void ConfigureServices(IServiceCollection services)
	{	
		services.AddSingleton<IGitHubApi>((sp) =>
			{
				return RestClient.For<IGitHubApi>("https://api.github.com");                
			});
	}
}	
public class GitHubUserRepository 
{
	private readonly IGitHubApi _api;

	public GitHubUserRepository(IGitHubApi api)
	{
		_api = api;
	}

	public async Task<User> Get(string id)
	{
	   return await _api.GetUserAsync(id);
	}
}
```

**Comment by canton7** [comment]
You shouldn't need a singleton instance. What issues were you seeing?

**Comment by Skylertodd** [comment]
When we would push this to azure, newing up the API interface in the
constructor, it would start failing to connect. Somewhat random but
patterned in groups. I ran a tcpview on my local as it was running in scale
and it appears to me like it is grabbing sockets left and right to make
outbound calls.

**Comment by canton7** [comment]
Ah yeah, I think I've heard about HttpClient doing that, although I've never seen it for myself. Making the RestEase interface IDisposable and making sure it's disposed might also help. I'd add a note.

**Comment by Skylertodd** [comment]
I was attempted the Idisposable implementation, which resulted in the same
behavior. In the web world, httpclient should be used in a pool or
singleton configuration. I believe creating and disposing of sockets is
expensive and will exhaust your available sockets at the OS level.
