### ISSUE TITLE
dnx

### ISSUE THREAD

**Issue by dgee2** [canton7/RestEase#6]
Hi,

Is any work being done to get this to work with dot net core?

Thanks

**Comment by canton7** [comment]
Not yet - I'm waiting for the dust to settle before diving too deep into .net core. If you have a particular need, I'd be happy to work with you to get something together. 

The main pain at the moment is needing TypeBuilder at runtime: I'm not sure what .net core provides here. I'm working on a feature to generate types at compile-time instead, which might help here...

**Comment by canton7** [comment]
I think this issue is superseded by #11.
