### ISSUE TITLE
Ability to disable URL encoding of Query String Parameter Values

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#61]
Question, is there a way to disable the URL encoding of the querystring parameter values?  

Note: I know I can pass in a raw querystring, and I know I can creating my own serializer -- I am just curious if there is an easier way.

Ex
```
Task<Response<string>> GetValue([Query("param", UrlEncode=false)] string value);
```

**Comment by canton7** [comment]
No, there isn't. What's the use-case?

**Comment by StefH** [comment]
A possible  solution could be to support url encoding on class level by using an attribute.

**Comment by canton7** [comment]
Solution to what? We don't know what the problem is yet.

**Comment by StefH** [comment]
I think that the author from this question just wants to **always disable URLEncoding for all calls** defined in the interface.

**Comment by canton7** [comment]
He didn't say that. Let's wait until the author actually describes what they're trying to do, and why.

**Comment by ravensorb** [comment]
Ok, I'll admit this might be a strange request -- however I am running into a number of internal applications that do not like it when query string parameter values are URL encoded.  So I was curious if there is an easy way on a per call or per param basis to disable the URL encoding process

**Comment by canton7** [comment]
I'm not sure I follow. If something is url encoded, then typically that's because if it wasn't url encoded the query string would not be valid. For example if you had the query parameter "foo&bar", and you didn't url encode it, you would get "thing=foo&bar", which the server would read as "foo" rather than as "foo&bar".

Do you have a specific example of a case where something has been url encoded, but would also be valid if it was not url encoded?

**Comment by ravensorb** [comment]
In theory -- I agree :)  However in practice, it's not always that cut and dry

Consider this
```http://someserver.com?url=http://www.google.com```

That is valid both URL encoded and not url encoded.  In my case, I need the "://" to NOT be url encoded due to some limitations on the remote side.

**Comment by canton7** [comment]
I'm somewhat loathe to give people an easily-discoverable way to turn off url encoding -- it's a footgun, as it makes it very easy to create a malformed URL, which might be hard to diagnose.

You can't avoid this by using a custom serializer either, as url encoding happens after serializing (for the same reason). You can use a raw query string, or subclass Requester and override BuildQueryParam, or use an interceptor, potentially.

Maybe I could make it easier to override the url encoding method particularly...

**Comment by StefH** [comment]
A custom `RequestQueryParamSerializer` could be:

```c#
public class CustomRequestQueryParamSerializer : RequestQueryParamSerializer
{
	public override IEnumerable<KeyValuePair<string, string>> SerializeQueryParam<T>(string name, T value, RequestQueryParamSerializerInfo info)
	{
		var list = new List<KeyValuePair<string, string>>();

		foreach (var propertyInfo in value.GetType().GetProperties())
		{
			list.Add(new KeyValuePair<string, string>(propertyInfo.Name, propertyInfo.GetValue(value, null).ToString()));
		}

		return list;
	}
}```

**Comment by canton7** [comment]
@StefH the url encoding is done by the Requester. There's nothing you can do in serializers to avoid url encoding.

Your requester iterates all properties on the parameter -- that has nothing to do with the question, no?

**Comment by Dolphinsimon** [comment]
I have met the same problem. 
There is a webapi  can not accept query string parameter values after url encoding.
It only accepts the raw + ,if the + turns to %2b. It will return an error with 'ParamException'.

**Comment by canton7** [comment]
Right, I'll break the URL encoding out into a helper which can be replaced.
