### ISSUE TITLE
Ability to mark query parameter as optional

### ISSUE THREAD

**Issue by modernist** [canton7/RestEase#62]
Would it be possible to allow query parameters to be marked as optional, so that if the value provided is null / empty the parameter is not appended in the query? It could be added as a boolean constructor parameter in the `Query` attribute

e.g. something like

```
public interface Test
{
    [Get("/test")]
    Task DoSomething([Query(Optional: true)]string param);
}
```

I know I can use a `[QueryMap]` and populate it as needed, but it would be useful in plenty of cases.

**Comment by canton7** [comment]
This should be the case already, by default? [Code](https://github.com/canton7/RestEase/blob/350e8c86dfd94d85e89a7e3c09ad5ce23b5af23f/src/RestEase/Implementation/QueryParameterInfo.cs#L135) [Test](https://github.com/canton7/RestEase/blob/350e8c86dfd94d85e89a7e3c09ad5ce23b5af23f/src/RestEaseUnitTests/RequesterTests/QueryParameterTests.cs#L30)

**Comment by modernist** [comment]
You're right, just ran some tests of my own. Sorry for the fuss.

**Comment by canton7** [comment]
No worries!

**Comment by canton7** [comment]
I should document this. Reopening to remind me.
