### ISSUE TITLE
Possible to default POST parameters to body+json?

### ISSUE THREAD

**Issue by awbacker** [canton7/RestEase#64]
Is it possible to, by default, send all paramters used on a post method as part of a JSON body?  Right now I find myself adding small classes for a lot of simple methods.   As an example

```
[Post("/api/stuff")]
async Task<StuffResponse> doStuff(string name, int age, bool is_hungry);

POST /api/stuff  
BODY { 
   "name": "Trent",
   "age" 55,
   "is_hungry", True
}
```

I can see some issues with this so I'm using parameter objects when sending right now, e.g. `new StuffRequest { name=... }`.

**Comment by canton7** [comment]
There's no way at the moment I'm afraid. I could imagine a new serializer type which could manage this.

However having said that, it would be possible (but very very hacky) to write a `RequestQueryParamSerializer` which modifies the content of the `info.RequestInfo.BodyParameterInfo.ObjectValue` parameter to alter the request body on-the-fly. Not entirely sure I'd recommend it....

For this sort of thing I've use [extension methods](https://github.com/canton7/RestEase#advanced-functionality-using-extension-methods).

**Comment by awbacker** [comment]
@canton7 Thanks for confirming that it's not directly possible.  I think I'll leave it for now and keep doing it the way I'm already doing it.  It sounds like this would be a more library level change, as you mentioned.

When I get adventurous, and the app is already working, I may do the extension method :)
