### ISSUE TITLE
RequestVoidAsync does not properly dispose HttpResponseMessage

### ISSUE THREAD

**Issue by annymsMthd** [canton7/RestEase#65]
RequestVoidAsync in Requester does not read the content so it needs to dispose of the HttpResponseMessage. We are seeing this in .net461 with a delete heavy workload using one HttpClient. It results in task canceled exceptions when the request finally times out.

**Comment by canton7** [comment]
Fair point! Thanks.

**Comment by canton7** [comment]
Fixed in 1.4.4, sorry for the delay!
