### ISSUE TITLE
Path part from body

### ISSUE THREAD

**Issue by netclectic** [canton7/RestEase#67]
Is it possible to pull a path part from an object passed in the body?
e.g. something like this...

```
public interface ISomeApi
{
    [Post("{user.ProjectId}/users/new")]
    Task CreateUserAsync([Body] User user);
}
```

where user.ProjectId is a property of the user object being passed in the body and is used to form part of the path?

**Comment by canton7** [comment]
No, it isn't I'm afraid. I recommend using [extension methods](https://github.com/canton7/RestEase#advanced-functionality-using-extension-methods).

**Comment by netclectic** [comment]
Excellent, I hadn't thought of that. A nice and simple solution too, thanks.

**Comment by canton7** [comment]
Closing, as I think this is resolved.
