### ISSUE TITLE
ModernHttpClient

### ISSUE THREAD

**Issue by sturlath** [canton7/RestEase#7]
Would you like to expose the Client to an injection of ModernHttpClient (https://github.com/paulcbetts/ModernHttpClient) (for mobile apps written in xamarin)? I like both your libraries and Im just wondering if it makes sense to "merge" them?

**Comment by canton7** [comment]
There's a `RestClient.For` overload which takes a custom HttpClient instance, which should be all you need to get it working, see here: https://github.com/canton7/RestEase/blob/master/README.md#custom-httpclient

That said, RestEase won't (currently) work on anything but .NET framework, as it requires a TypeBuilder at runtime. I've got plans to relax that, but the code isn't filly written yet.

**Comment by canton7** [comment]
Any response?

**Comment by canton7** [comment]
Closing as no response.
