### ISSUE TITLE
How to handle a response that could be either single or an array?

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#75]
Ok, so here is a fun one :)

I need to access server API end points that handle return messages with arrays a bit differently.  The issue is that the response object either has a collection or a property depending on if the collection has 1 or more than 1 items.

```
{
  item: [
     { },
     { },
  ]
}
```
or
```
{
   item: {}
}
```

You can see the following article on how this can be handled in general.

https://stackoverflow.com/questions/18994685/how-to-handle-both-a-single-item-and-an-array-for-the-same-property-using-json-n

The question I have is -- what is the best way to handle this in a response message if I want to continue using the Task<Response<T>> approach?

Am I forced to implement a custom Response Serializer?

**Comment by canton7** [comment]
You can follow the top answer in that SO post without using a custom deserializer: just write the right JsonConverter and decorate your response type with the right attributes

**Comment by ravensorb** [comment]
Tried that :)  I set in my case its on the root object.

Example
```
Task<Response<List<ApiResponse>>> GetItems();
```

**Comment by canton7** [comment]
The custom response deserializer just does `JsonConvert.Deserialize<List<ApiResponse>>`. If you can get an example working with `JsonConvert.Deserialize` (and it looks like you can, from the SO post), then it will work with RestEase with no extra work.

Anyway, this is between you and Json.NET -- I'm afraid I don't provide support for Json.NET.
