### ISSUE TITLE
Mapping response attributes when the name has spaces or other characters not allowed in c#

### ISSUE THREAD

**Issue by MartinCairnsSQL** [canton7/RestEase#76]
Is it possible to map attributes with names which aren't compatible with c# naming rules?

In the response fragment below, I can't workout how to map the values for "last use date" and "create date" on to my c# class.

`{
            "last use date": "2017-11-26T00:08:00",
            "create date": "2017-11-08T21:44:23",
            "name": "hue-hca-actions-on-google"
}`

**Comment by canton7** [comment]
So the default json serializer/deserializer uses Json.NET, which lets you do that using `JsonAttribute`.

**Comment by MartinCairnsSQL** [comment]
Thanks, that worked.
