### ISSUE TITLE
Headers not added on redirect

### ISSUE THREAD

**Issue by borrrden** [canton7/RestEase#77]
I noticed that if I set up an interface method to an endpoint which returns a 301 (Moved Permanently) the underlying client follows the redirect, but does not send the headers in the interface on the second attempt.  This is a property based Header as follows.

```
[Header("Cookie")]
string AuthCookie { get; set; }
````

Is this expected or am I missing a setting somewhere?

**Comment by canton7** [comment]
This isn't expected, but it's HttpClient which is managing the redirect, so I'd have to investigate why it isn't sending the second time...

**Comment by canton7** [comment]
(Looks like this is intentional for security reasons, see e.g. https://stackoverflow.com/a/28671822/1086121)

**Comment by canton7** [comment]
Closing as this isn't my issue.
