### ISSUE TITLE
Cant get it to work in a console app

### ISSUE THREAD

**Issue by ozzioma** [canton7/RestEase#8]
Hi,
Been trying to use this lib to access several rest endpoints from a console app.
Nothing happens, like nada, not even an exception is thrown.
Wrapped the async methods using several techniques in the main method,
still nothing happens.
Any pointers as to how I might get it working from a console app?

Thanks,
Ozzy

**Comment by canton7** [comment]
Here's a quick example of using it from the command line:

```csharp
public class User
{
    [JsonProperty("login")]
    public string Login { get; set; }

    [JsonProperty("id")]
    public int Id { get; set; }

    [JsonProperty("url")]
    public string Url { get; set; }
}

[Header("User-Agent", "RestEase")]
public interface IGitHubApi
{
    [Get("/users/{userId}")]
    Task<User> GetUserAsync([Path] string userId);
}

public class Program
{
    public static void Main()
    {
        var api = RestClient.For<IGitHubApi>("https://api.github.com");
        var user = api.GetUserAsync("canton7").Result;
        Console.WriteLine("Login: {0}, ID: {1}, URL: {2}", user.Login, user.Id, user.Url);
        Console.ReadLine();
    }
}
```

**Comment by ozzioma** [comment]
Hi,
Thanks for the quick response.
Tried all that previously, still did not work.
This is the API I'm trying to call:
https://dev.infobip.com/docs/send-single-sms

Can successfully call it from RestSharp and using raw http requests, however RestEase's abstraction
is simply elegant...just need to get it to work.
Would appreciate any pointers.

Thanks,
Ozzy

**Comment by ozzioma** [comment]
Hi,
Never mind.
Missed the [Body] attribute on the method definition.
Working now.

Thanks for sharing!
Ozzy

**Comment by canton7** [comment]
I wonder why it was hanging then... I'll try and reproduce this when I get some free time.

**Comment by canton7** [comment]
How long did you leave it for, by the way? Is it possible the remote side wasn't responding, but the request hadn't timed out yet?

**Comment by ozzioma** [comment]
Hi Antony,
Its working now.
I actually forgot to add the [Body] attribute to the request object in the method signature.
That was the missing piece for me...figured it out finally.
@timeout not started profiling yet...so no timeouts yet. Will alert you if I notice any.

Thanks for responding!
Ozzy

**Comment by canton7** [comment]
I mean, even without `[Body]` it shouldn't have frozen as you described. I know everything's now working for you, but I'm trying to work out *why* it froze without `[Body]`.

**Comment by ozzioma** [comment]
Ok.
Was wondering too. It should have thrown an exception at the minimum.

**Comment by canton7** [comment]
Missing out `[Body]` is not something which should cause an exception to be thrown: it just gets sent as a query parameter rather than as the body of the request. While in this case that isn't what you wanted, it might have been, and should still have sent the request successfully.

**Comment by canton7** [comment]
Closing as no response.
