### ISSUE TITLE
Timeout for underlying HttpClient instance

### ISSUE THREAD

**Issue by MykhailoKyrychenko** [canton7/RestEase#80]
Hi,

Thank you for your project!

It looks, like current implementation uses default timeout for HttpClient, if last one is not overridden during api client generation.

However, such functionality could be helpful when you using request modifier and the only thing you need to override in HttpClient is request's time out.

My proposition is to add overrides to fabric methods with timeout argument.

What do you think about it?

**Comment by canton7** [comment]
I'm afraid it's not clear what you're asking for.

> My proposition is to add overrides to fabric methods with timeout argument.

What's a "fabric method"?

**Comment by MykhailoKyrychenko** [comment]
You have different types of overrides for
`RestClient.For<T>` method such as
`For<T>(IRequester requester)
For<T>(string baseUrl)
For<T>(Uri baseUrl)
For<T>(HttpClient httpClient)
For<T>(string baseUrl, RequestModifier requestModifier)`
and so on

**Comment by canton7** [comment]
Just do:

```csharp
var httpClient = new HttpClient(new ModifyingClientHttpHandler(someRequestModifier))
{
    BaseAddress = new Uri("http://example.com"),
    Timeout = TimeSpan.FromMinutes(5),
    
};
var client = RestClient.For<T>(httpClient);
```

**Comment by MykhailoKyrychenko** [comment]
Looks like a good solution. Thanks for assist!
