### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by wconnors77** [canton7/RestEase#83]
At the very top of the code page, it says "Easy-to-use typesafe REST API client library for .NET Core". Does that mean that if I have a visual studio 2017 solution, .NET framework 4.5.2 project, I can't use RestEase?

**Comment by canton7** [comment]
Where does it say that?

The very start of the README says:

> RestEase is a little type-safe REST API client library for .NET Framework 4.5 and higher and .NET Platform Standard 1.1

**Comment by wconnors77** [comment]
![snag-20180302-170916](https://user-images.githubusercontent.com/36974478/36927699-839fe7b0-1e3c-11e8-90ee-1c425e1694ba.jpg)

**Comment by phillijw** [comment]
`<TargetFrameworks>netstandard1.1;net45</TargetFrameworks>`

The target framework implies it will work with .net 4.5

**Comment by canton7** [comment]
Yep, as my last message quoted from the README (although I think github decided to collapse it by default):

> RestEase is a little type-safe REST API client library for .NET Framework 4.5 and higher and .NET Platform Standard 1.1

**Comment by phillijw** [comment]
I think you may have to explicitly list all newer versions as well. Might be a super easy fix if people are having issues with that.

**Comment by canton7** [comment]
The issue here is that the banner at the top was incorrect (and has now been corrected), no? It said ".NET Core", when in fact it targeted .NET Standard and Framework, not Core

**Comment by phillijw** [comment]
Gotcha. I think that's fine. My concern was over the fact that he was targeting 4.5.2 but the library specifically targeted 4.5. I wasn't sure it would allow all newer as well as it's not clear in the MSFT docs

**Comment by canton7** [comment]
Yes, I think most people are familiar with how .NET's backwards compatibility works, so I don't think it's necessary to spell it out here (and keep it updated with all new framework and standard versions which are released)

**Comment by StefH** [comment]
Another remark (related):
Technically it's possible to use a 1.1 dependency in a 2.0 project, however, as a library provider, it's good to limit the external NuGet depenencies as much as possible. So my suggestion is to also add netstandard 2,0 in the csproj.

If you want to check this, just open the generated `nupkgfile` with [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and check out the listed dependencies.

**Comment by canton7** [comment]
If you want to propose this, please open a new issue and list the dependencies which could be removed. Thanks!

**Comment by StefH** [comment]
Done, see https://github.com/canton7/RestEase/issues/88

**Comment by canton7** [comment]
Thanks! Closing this issue, as I've fixed it.
