### ISSUE TITLE
Include URI parameters in ApiException message

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [canton7/RestEase#85]
Given a client declaration:
```csharp
    public interface SomeRestClient
    {
        [Get("v1/foo/{id}")]
        Task<Foo> GetBar([Path(Name="id")] string id);
    }
```
If something goes wrong (e.g. server returns 404) RestEase throws an `ApiException` with a message similar to `v1/foo/ failed.`. So as you can see the actual `id` query parameter is not included in the exception message. This forces me to log both query parameter and the exception message. It would be much more better to include all URI parameters into the exception message like `v1/foo/123 failed.`.

**Comment by canton7** [comment]
Can't you look at the RequestUri property of the ApiException?

I will add those properties to Exception.Data...

**Comment by canton7** [comment]
The exception message should contain the full URI which was requested as well, including all parameters. If you're not seeing a parameter there, it's because you didn't pass one into `GetBar`.

**Comment by canton7** [comment]
Closing as no response.
