### ISSUE TITLE
Build time codegen

### ISSUE THREAD

**Issue by galvesribeiro** [canton7/RestEase#87]
Hello,

I know from the README.md that RestEase doesn't support AOT platform as it does runtime codegen.

I think it could have an approach similar to what we have in Orleans which is have an external package which essentially is an MSBuild task that invoke the codegen code to run at build time and add the generated types to /obj/something and add it to the final compiled assembly. It would be optional and the runtime codegen would check for the already generated code and just skip it. That would not even remove the need to generate at runtime if people don't want to, but would allow support to AOT-based platforms.

Would that be considered as a PR?

Thanks! Great work on this library!

**Comment by canton7** [comment]
There's a long term goal to use Fody to do compile-time code generation. However it's a big task, as all of the Reflection.Emit stuff (and there's a lot of it) needs to be rewritten to use mono.ceceil. One of the big advantages of using Fody is we get to inject the implementations straight into the user's assembly, meaning no confusing second dll, and we can implement internal interfaces.

I started some refactoring work to break up the logic from the actual IL emission in ImplementationBuilder, as a first step towards a mono.ceceil implementation, but never finished it. I'm also toying with the idea of simplifying the ImplementationBuilder and moving its logic to runtime reflection.

**Comment by galvesribeiro** [comment]
We use Roslyn in Orleans for both runtime and buildtime codegeneration (https://github.com/dotnet/orleans/tree/master/src/Orleans.CodeGeneration). The codegen itself is on its own assembly and is invoked by an MSBuild task or if no generated code is found at initialization, it will run at runtime.

I think instead of use Mono.Ceceil use a model based on Roslyn would have best support going forward.

**Comment by canton7** [comment]
I did look at that, but Roslyn is a large dependency to force people to include, and the feedback I got was that people didn't want that.

**Comment by canton7** [comment]
RestEase.SourceGenerator has just been released, which uses a source generator to do AOT codegen.
