### ISSUE TITLE
[Body] with key?

### ISSUE THREAD

**Issue by diegoRodriguezAguila** [canton7/RestEase#9]
Hello,

Is there a way to explicity set a key for a body param, without url encoding? 
The problem is that I have a Json Api, which expects certain json body params (one of them is an array), with certain keys. 
For now as a workaround I'm sending it in the Query, but I have to encode the array and parse it in the client and server as follows: `?stuff_key=bla1,bla2`, and as stated before, I wouldn't really want to send it via query/url.
I think it would rather be simplier to send  `stuff_key: ["bla1", "bla2",...]` in the body.

It would be great to have something like

```csharp
([Body("stuff_key")] IList<string> stuff)
```

**Comment by canton7** [comment]
I'm slightly confused: you've got a API which you can either send data to as a query parameter, *or* in the body? That's quite unusual.

`stuff_key: ["bla1", "bla2",...]` is not any standard form of encoding. `{"stuff_key: ["blah1", "blah2", ...]}` would be JSON-encoded data, while `stuff_key=blah1&stuff_key=blah2` would be URL-encoded data.

**Comment by diegoRodriguezAguila** [comment]
Well, it's a workaround to send it in the query, all the other endpoints receive the json via body, thus I had to modify the server, in order to receive it via query. And indeed, I was refering to `{"stuff_key": ["blah1", "blah2", ...]}` , (sorry, it's my fault I oversimplified the example, the body always has a wrapper object).

When you specify a body object for example: `[Body] Rule rule` , RestEase encodes it using the name of the variable: `{"rule": { "action": "permit", ...}}` 
 but if I send an array, for example `[Body] IList<string> ids` it doesn't encode it as expected, it sets a default key: `_json`  => `{"_json": ["id1", "id2"]}`  and should be `{"ids": ["id1", "id2"]}`.

Because of this, I wanted to know if there is a way to specify the key for the body, like `([Body("identifiers")] IList<string> ids)` which would encode it as  `{"identifiers": ["id1", "id2"]}`.

I hope this time I was clear enough and thank you in advance.

PD: My server is Ruby on Rails 4.2 if that makes any difference

**Comment by canton7** [comment]
This is JSON.NET deciding how to serialize your object.

Create a new class, e.g.

```csharp
class BodyContent
{
    [JsonProperty("identifiers")]
    public List<string> Ids { get; set; }
}
```

and pass this as the body: `([Body] BodyContent body)`.

Another approach would be to create your own custom [IRequestBodySerializer](https://github.com/canton7/RestEase#serializing-request-bodies-irequestbodyserializer), which takes the input object, wraps it in a `BodyContent`-like class, and passes *that* to JSON.NET.

In order to do exactly what you ask, I'd have to make all sorts of assumptions about the body being structured as JSON, which I don't want to do: the idea is you pass in an object, and the serializer which RestEase has been configured with (which uses JSON.NET by default, but that can be changed completely) takes charge of serializing it.

**Comment by diegoRodriguezAguila** [comment]
Yes, I was about to figuring out I would have to do something like your first suggestion, but if I have other names for the lists (ie. `{"uids": []}`) I would have to create a lot of wrapper objects with distinct names, or using reflection to change the annotation at runtime.

I think I'll go with the `IRequestBodySerializer` option, thank you very much, that's what I needed.

**Comment by canton7** [comment]
One of the advantages (and aims) of RestEase is that it's very easy to see the structure of the API by looking at the interface you write for it: if a method takes a particular data type, that is declared upfront, and everything's very clear.

In this spirit, it makes sense to have a UuidList` and an `IdList`, etc: this makes life easier for someone reading you code and trying to figure out what it's sending to the API.

OTOH, too much boilerplate becomes annoying fast...
