### ISSUE TITLE
Generic method

### ISSUE THREAD

**Issue by BizyDev** [canton7/RestEase#92]
Hello,

Firstly, thank you for this awesome library, it's a pleasure to work with.

Secondly, I work with a very poorly designed API, and have one question about generic interfaces. I saw in the docs that we can do this : 

``` csharp
public interface IReallyExcitingCrudApi<T, TKey>
{
    [Post("")]
    Task<T> Create([Body] T paylod);

    [Get("")]
    Task<List<T>> ReadAll();

    [Get("{key}")]
    Task<T> ReadOne(TKey key);

    [Put("{key}")]
    Task Update(TKey key, [Body]T payload);

    [Delete("{key}")]
    Task Delete(TKey key);
}
```

What I would like to achieve is this : 

``` csharp
public interface IReallyExcitingCrudApi
{
    [Post("BlaBla")]
    Task<T> GenericRequest<T>([Body] BaseRequest req);
}
```
In this very well designed API there's only one endpoint, all request are sent by post, the only differences are in request body and return types. Inherit all my request from `BaseRequest` it's ok for me and it works fine. The problems is with return type, when I run a request like this one RestEase throws the following exception : 

>RestEase.Implementation.ImplementationCreationException: 'Unable to create implementation for interface BlaBla.IBlaBlaApi. Ensure that the interface is public, or add [assembly: InternalsVisibleTo(RestClient.FactoryAssemblyName)] to your AssemblyInfo.cs'

Inner exception :

>TypeLoadException: Signature of the body and declaration in a method implementation do not match.  Type: 'RestEase.AutoGenerated.<>Bla+Bla+IBlaBlaApi'.  Assembly: 'RestEaseFactory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Is my idea compatible with RestEase or am I missing something obvious ?

Thanks in advance for your help and thanks again for such an amazing library.

**Comment by canton7** [comment]
There's currently no support for generic methods like that, although I'd be up for adding it!

**Comment by R0xtar** [comment]
Okay sorry
