### ISSUE TITLE
Better exception when interface is mark internal. Exception: Duplicate type name within an assembly

### ISSUE THREAD

**Issue by maartenmensink** [canton7/RestEase#93]
When defining a interface for the API i the interface marked as internal as the rest of my code didn't require it to be public.

When calling `RestClient.For<IApi>(url);` i got a exception `Duplicate type name within an assembly` 

```
internal interface IApi
{
     [Get]
     Task<Result> Method();
}
```

It would be helpful to get a specific exception that this wasn't my brightest idea 😄

**Comment by canton7** [comment]
There's something else going on: you get a different exception if you try and use an internal interface, which does talk about making sure it's public. It's possible that you called RestClient.For on that internal type twice, and got this exception the second time.

Annoyingly I can't just check whether the interface is public, as its possible to use an assembly attribute to use internal types.

Maybe the thing to do is to store the exception which occurred the first time you tried to call RestClient.For, and rethrow it if you call it again with the same type. At lest then you get a consistent exception.
