### ISSUE TITLE
Add an attribute to method which enables custom input parameter validation?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#96]
I've defined this interface API
``` c#
public interface IInfuraTickerApi
{
    [Validate(typeof(InfuraTickerApiValidation))] // New !?
    Task<TickerResponse> GetSymbolAsync([NotNull, Path] string symbol);
}
```

Would it be possible to defined a new attribute `Validate()` or `Callback()` which takes a class which implements the API interface and does some validation or other callback functionality ?

This class could look like:
``` c#
public class InfuraTickerApiValidation : IInfuraTickerApi
{
    public async Task<TickerResponse> GetSymbolAsync(string symbol)
    {
        if (string.IsNullOrEmpty(symbol))
        {
            throw new ArgumentNullException(nameof(symbol));
        }
        return null;
    }
}
```

**Comment by canton7** [comment]
No. RestEase is a simple way to access an API. It is no more than that.

If you need more, you should write your own data access layer which uses RestEase internally.

**Comment by StefH** [comment]
Still it would be very useful if a `RestEaseCallbackAttribute` would be added to this library, like this:

``` c#
public interface IInfuraTickerApi
{
    [RestEaseCallback(....))] // define here the class which implements the IRestEaseCallback interface
    Task<TickerResponse> GetSymbolAsync([NotNull, Path] string symbol);
}
```

``` c#
public interface IRestEaseCallback<T>
{
    void Execute(T api, IRequestInfo requestInfo);
}
```
And this `Execute` method would be executed **before** the request is send using HttpClient.


Currently the classes in your library are to closed or only have private methods, so I cannot achieve the logic I want.
I tried like this:
``` c#
IInfuraApi api = ...;
var fields = api.GetType().GetRuntimeFields();
var requesterField = fields.FirstOrDefault();
IRequester requester = (Requester)requesterField.GetValue(api);
var implementation = ImplementationBuilder.Instance.CreateImplementation<IInfuraApi>(requester);

// ?
IRequestInfo i = new RequestInfo(HttpMethod.Get, "https://api.infura.io/v1/ticker/symbols");

// 1. call custom validation method?
// 2. call the api
var response = await requester.RequestAsync<SymbolsResponse>(i);
```

**Comment by canton7** [comment]
Again, I don't think parameter validation is the responsibility of RestEase.

I think what you are already trying to do is supported, but subclassing Requester and overriding SendRequestAsync, [as described in the docs](https://github.com/canton7/RestEase/blob/master/README.md#customizing-restease). Whatever you're trying to do with calling ImplementationBuilder is not in the docs and is not supported.
