### ISSUE TITLE
How to construct RestEase response for purposes of mocking function?

### ISSUE THREAD

**Issue by nguillermin** [canton7/RestEase#97]
I'm using Moq to mock an API for some unit testing. However, when I try to setup the functions, I need to ReturnsAsync a RestEase response. Now constructing a RestEase response seems to be trickier than I thought.

![image](https://user-images.githubusercontent.com/2622768/41743420-b75ecfce-756e-11e8-8182-519edf117b72.png)

What am I supposed to put as the deserializer Func? The content (which won't be an empty string eventually) should be JSON, but I'm not sure how to gain access to the right thing from the RestEase default JSON deserializer.

**Comment by canton7** [comment]
So your API looks something like this?

```csharp
public interface IVeracrossAPI
{
    Task<Response<List<VeracrossStudent>>> GetStudentsAsync(stuff);
}
```

That `Func<List<VeracrossStudent>>` is just a func which creates the returned deserialized object. An implementation might be `() => new List<VeracrossStudent>() { new VeracrossStudent("Bob") }`

`Response<T>` is a very simple data object which [looks like this](https://github.com/canton7/RestEase/blob/master/src/RestEase/Response.cs). It's got properties which hold the returned string, the returned HttpResponseMessage, and a delegate which returns the deserialized content.

**Comment by canton7** [comment]
Closing as I think this is answered.
