### ISSUE TITLE
Optional Parameters from IronPython

### ISSUE THREAD

**Issue by netclectic** [canton7/RestEase#98]
Any idea as to why when I call a RestEase generated method from IronPython it doesn't respect my optional query parameters?

```        [Get("/my_method")]
        Task<MyThing> MyMethod(
            [Query] bool? param1 = null,
            [Query] string param2 = null,
            [Query] string param3 = null,
            [Query] string param4 = null
            );
```

It works fine from a standard C# client, but from my embedded IronPython client it tells me
`MyMethod() takes exactly 4 arguments (0 given)`

IronPython generally respects optional parameters and if I pass null values in it works fine.

Is there some 'magic' happening in the code generation that means the parameters are not actually optional in the resulting method?

**Comment by canton7** [comment]
No idea. Optional parameters in C# are encoded at the level of the interface here.

Does IronPython normally work if you define optional arguments on an interface?

**Comment by netclectic** [comment]
That'll explain it... Python doesn't care about types or interfaces, as it's fully dynamic or 'duck typed': 

> If it walks like a duck and it quacks like a duck, then it must be a duck

```
    public interface IMyThing
    {
        string DoStuffWithOrWithoutAParam(string param = null);
    }

    public class MyThing : IMyThing
    {
        public string DoStuffWithOrWithoutAParam(string param = null)
        {
            return string.Format("Hello {0}", string.IsNullOrWhiteSpace(param) ? "World" : param);
        }
    }

    public class MyBrokenThing : IMyThing
    {
        public string DoStuffWithOrWithoutAParam(string param)
        {
            return string.Format("Hello {0}", string.IsNullOrWhiteSpace(param) ? "World" : param);
        }
    }
```

So, the first implementation works from IronPython but the second one doesn't.
Strangely, I've been working with IronPyhton for about 6 years now and have never come across this before now.

**Comment by canton7** [comment]
Ah, right. I might be able to do something about that: I'll have a look.

**Comment by canton7** [comment]
Mind trying this build? https://ci.appveyor.com/project/canton7/restease/build/1.4.5.309

**Comment by netclectic** [comment]
Awesome! That works perfectly, thanks :-)

**Comment by canton7** [comment]
Cool, thanks for checking. That will be in the next release.

**Comment by canton7** [comment]
Hi @netclectic. Are you still using IronPython with RestEase?

If so, I've got a quick question, if you don't mind: I'm considering moving to have the generated implementation explicitly implementing the interface methods (to avoid some issues with interface inheritance, where two inherited methods define incompatible methods). Is this going to affect late-bound languages like IronPython?

**Comment by netclectic** [comment]
Hello, yes I am still using IronPython with RestEase.

Its not something I'd encountered before so had to go look it up. After testing it, I can confirm that IronPython can handle calling conflicting methods with explicit interfaces. 

Its something the caller has to be aware of because the syntax is quite different, but I think that would be the same even in native c#.

**Comment by canton7** [comment]
Thanks for checking!

In C# there's no difference here, since you're calling through an instance of the interface. 

It sounds like I'm going to have to keep implicitly implementing the interface where possible, and detect conflicting methods/properties and implement those explicitly.
